// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/venue/internal/kitchen"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDishes creates a new instance of MockDishes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDishes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDishes {
	mock := &MockDishes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDishes is an autogenerated mock type for the Dishes type
type MockDishes struct {
	mock.Mock
}

type MockDishes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDishes) EXPECT() *MockDishes_Expecter {
	return &MockDishes_Expecter{mock: &_m.Mock}
}

// Give provides a mock function for the type MockDishes
func (_mock *MockDishes) Give(ctx context.Context, sku string, qty int) (kitchen.Dish, error) {
	ret := _mock.Called(ctx, sku, qty)

	if len(ret) == 0 {
		panic("no return value specified for Give")
	}

	var r0 kitchen.Dish
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (kitchen.Dish, error)); ok {
		return returnFunc(ctx, sku, qty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) kitchen.Dish); ok {
		r0 = returnFunc(ctx, sku, qty)
	} else {
		r0 = ret.Get(0).(kitchen.Dish)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, sku, qty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDishes_Give_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Give'
type MockDishes_Give_Call struct {
	*mock.Call
}

// Give is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - qty int
func (_e *MockDishes_Expecter) Give(ctx any, sku any, qty any) *MockDishes_Give_Call {
	return &MockDishes_Give_Call{Call: _e.mock.On("Give", ctx, sku, qty)}
}

func (_c *MockDishes_Give_Call) Run(run func(ctx context.Context, sku string, qty int)) *MockDishes_Give_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDishes_Give_Call) Return(dish kitchen.Dish, err error) *MockDishes_Give_Call {
	_c.Call.Return(dish, err)
	return _c
}

func (_c *MockDishes_Give_Call) RunAndReturn(run func(ctx context.Context, sku string, qty int) (kitchen.Dish, error)) *MockDishes_Give_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDishes
func (_mock *MockDishes) List(ctx context.Context) ([]kitchen.Dish, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []kitchen.Dish
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]kitchen.Dish, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []kitchen.Dish); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]kitchen.Dish)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDishes_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDishes_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDishes_Expecter) List(ctx any) *MockDishes_List_Call {
	return &MockDishes_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDishes_List_Call) Run(run func(ctx context.Context)) *MockDishes_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDishes_List_Call) Return(dishs []kitchen.Dish, err error) *MockDishes_List_Call {
	_c.Call.Return(dishs, err)
	return _c
}

func (_c *MockDishes_List_Call) RunAndReturn(run func(ctx context.Context) ([]kitchen.Dish, error)) *MockDishes_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetAvailable provides a mock function for the type MockDishes
func (_mock *MockDishes) SetAvailable(ctx context.Context, sku string, available bool) (kitchen.Dish, error) {
	ret := _mock.Called(ctx, sku, available)

	if len(ret) == 0 {
		panic("no return value specified for SetAvailable")
	}

	var r0 kitchen.Dish
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (kitchen.Dish, error)); ok {
		return returnFunc(ctx, sku, available)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) kitchen.Dish); ok {
		r0 = returnFunc(ctx, sku, available)
	} else {
		r0 = ret.Get(0).(kitchen.Dish)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, sku, available)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDishes_SetAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAvailable'
type MockDishes_SetAvailable_Call struct {
	*mock.Call
}

// SetAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - available bool
func (_e *MockDishes_Expecter) SetAvailable(ctx any, sku any, available any) *MockDishes_SetAvailable_Call {
	return &MockDishes_SetAvailable_Call{Call: _e.mock.On("SetAvailable", ctx, sku, available)}
}

func (_c *MockDishes_SetAvailable_Call) Run(run func(ctx context.Context, sku string, available bool)) *MockDishes_SetAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDishes_SetAvailable_Call) Return(dish kitchen.Dish, err error) *MockDishes_SetAvailable_Call {
	_c.Call.Return(dish, err)
	return _c
}

func (_c *MockDishes_SetAvailable_Call) RunAndReturn(run func(ctx context.Context, sku string, available bool) (kitchen.Dish, error)) *MockDishes_SetAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Take provides a mock function for the type MockDishes
func (_mock *MockDishes) Take(ctx context.Context, sku string, qty int) (kitchen.Dish, error) {
	ret := _mock.Called(ctx, sku, qty)

	if len(ret) == 0 {
		panic("no return value specified for Take")
	}

	var r0 kitchen.Dish
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (kitchen.Dish, error)); ok {
		return returnFunc(ctx, sku, qty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) kitchen.Dish); ok {
		r0 = returnFunc(ctx, sku, qty)
	} else {
		r0 = ret.Get(0).(kitchen.Dish)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, sku, qty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDishes_Take_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Take'
type MockDishes_Take_Call struct {
	*mock.Call
}

// Take is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - qty int
func (_e *MockDishes_Expecter) Take(ctx any, sku any, qty any) *MockDishes_Take_Call {
	return &MockDishes_Take_Call{Call: _e.mock.On("Take", ctx, sku, qty)}
}

func (_c *MockDishes_Take_Call) Run(run func(ctx context.Context, sku string, qty int)) *MockDishes_Take_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDishes_Take_Call) Return(dish kitchen.Dish, err error) *MockDishes_Take_Call {
	_c.Call.Return(dish, err)
	return _c
}

func (_c *MockDishes_Take_Call) RunAndReturn(run func(ctx context.Context, sku string, qty int) (kitchen.Dish, error)) *MockDishes_Take_Call {
	_c.Call.Return(run)
	return _c
}
