// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/venue/internal/kitchen"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrders creates a new instance of MockOrders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrders {
	mock := &MockOrders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrders is an autogenerated mock type for the Orders type
type MockOrders struct {
	mock.Mock
}

type MockOrders_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrders) EXPECT() *MockOrders_Expecter {
	return &MockOrders_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockOrders
func (_mock *MockOrders) Get(ctx context.Context, id uuid.UUID) (kitchen.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 kitchen.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (kitchen.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) kitchen.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(kitchen.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrders_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrders_Expecter) Get(ctx any, id any) *MockOrders_Get_Call {
	return &MockOrders_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrders_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrders_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_Get_Call) Return(order kitchen.Order, err error) *MockOrders_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrders_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (kitchen.Order, error)) *MockOrders_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function for the type MockOrders
func (_mock *MockOrders) Move(ctx context.Context, id uuid.UUID, from kitchen.State, to kitchen.State) (bool, error) {
	ret := _mock.Called(ctx, id, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, kitchen.State, kitchen.State) (bool, error)); ok {
		return returnFunc(ctx, id, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, kitchen.State, kitchen.State) bool); ok {
		r0 = returnFunc(ctx, id, from, to)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, kitchen.State, kitchen.State) error); ok {
		r1 = returnFunc(ctx, id, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockOrders_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - from kitchen.State
//   - to kitchen.State
func (_e *MockOrders_Expecter) Move(ctx any, id any, from any, to any) *MockOrders_Move_Call {
	return &MockOrders_Move_Call{Call: _e.mock.On("Move", ctx, id, from, to)}
}

func (_c *MockOrders_Move_Call) Run(run func(ctx context.Context, id uuid.UUID, from kitchen.State, to kitchen.State)) *MockOrders_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 kitchen.State
		if args[2] != nil {
			arg2 = args[2].(kitchen.State)
		}
		var arg3 kitchen.State
		if args[3] != nil {
			arg3 = args[3].(kitchen.State)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrders_Move_Call) Return(b bool, err error) *MockOrders_Move_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrders_Move_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, from kitchen.State, to kitchen.State) (bool, error)) *MockOrders_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Ripe provides a mock function for the type MockOrders
func (_mock *MockOrders) Ripe(ctx context.Context, due []kitchen.Due, limit int) ([]kitchen.Order, error) {
	ret := _mock.Called(ctx, due, limit)

	if len(ret) == 0 {
		panic("no return value specified for Ripe")
	}

	var r0 []kitchen.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []kitchen.Due, int) ([]kitchen.Order, error)); ok {
		return returnFunc(ctx, due, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []kitchen.Due, int) []kitchen.Order); ok {
		r0 = returnFunc(ctx, due, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]kitchen.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []kitchen.Due, int) error); ok {
		r1 = returnFunc(ctx, due, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Ripe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ripe'
type MockOrders_Ripe_Call struct {
	*mock.Call
}

// Ripe is a helper method to define mock.On call
//   - ctx context.Context
//   - due []kitchen.Due
//   - limit int
func (_e *MockOrders_Expecter) Ripe(ctx any, due any, limit any) *MockOrders_Ripe_Call {
	return &MockOrders_Ripe_Call{Call: _e.mock.On("Ripe", ctx, due, limit)}
}

func (_c *MockOrders_Ripe_Call) Run(run func(ctx context.Context, due []kitchen.Due, limit int)) *MockOrders_Ripe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []kitchen.Due
		if args[1] != nil {
			arg1 = args[1].([]kitchen.Due)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrders_Ripe_Call) Return(orders []kitchen.Order, err error) *MockOrders_Ripe_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrders_Ripe_Call) RunAndReturn(run func(ctx context.Context, due []kitchen.Due, limit int) ([]kitchen.Order, error)) *MockOrders_Ripe_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrders
func (_mock *MockOrders) Save(ctx context.Context, placed kitchen.OrderCreated) (bool, error) {
	ret := _mock.Called(ctx, placed)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kitchen.OrderCreated) (bool, error)); ok {
		return returnFunc(ctx, placed)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, kitchen.OrderCreated) bool); ok {
		r0 = returnFunc(ctx, placed)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, kitchen.OrderCreated) error); ok {
		r1 = returnFunc(ctx, placed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrders_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - placed kitchen.OrderCreated
func (_e *MockOrders_Expecter) Save(ctx any, placed any) *MockOrders_Save_Call {
	return &MockOrders_Save_Call{Call: _e.mock.On("Save", ctx, placed)}
}

func (_c *MockOrders_Save_Call) Run(run func(ctx context.Context, placed kitchen.OrderCreated)) *MockOrders_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kitchen.OrderCreated
		if args[1] != nil {
			arg1 = args[1].(kitchen.OrderCreated)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_Save_Call) Return(b bool, err error) *MockOrders_Save_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrders_Save_Call) RunAndReturn(run func(ctx context.Context, placed kitchen.OrderCreated) (bool, error)) *MockOrders_Save_Call {
	_c.Call.Return(run)
	return _c
}
