// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPartnerClient creates a new instance of MockPartnerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartnerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartnerClient {
	mock := &MockPartnerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartnerClient is an autogenerated mock type for the PartnerClient type
type MockPartnerClient struct {
	mock.Mock
}

type MockPartnerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartnerClient) EXPECT() *MockPartnerClient_Expecter {
	return &MockPartnerClient_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) Accept(ctx context.Context, orderID uuid.UUID, eta int) error {
	ret := _mock.Called(ctx, orderID, eta)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, orderID, eta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartnerClient_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockPartnerClient_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - eta int
func (_e *MockPartnerClient_Expecter) Accept(ctx any, orderID any, eta any) *MockPartnerClient_Accept_Call {
	return &MockPartnerClient_Accept_Call{Call: _e.mock.On("Accept", ctx, orderID, eta)}
}

func (_c *MockPartnerClient_Accept_Call) Run(run func(ctx context.Context, orderID uuid.UUID, eta int)) *MockPartnerClient_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPartnerClient_Accept_Call) Return(err error) *MockPartnerClient_Accept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartnerClient_Accept_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, eta int) error) *MockPartnerClient_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Handover provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) Handover(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Handover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartnerClient_Handover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handover'
type MockPartnerClient_Handover_Call struct {
	*mock.Call
}

// Handover is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockPartnerClient_Expecter) Handover(ctx any, orderID any) *MockPartnerClient_Handover_Call {
	return &MockPartnerClient_Handover_Call{Call: _e.mock.On("Handover", ctx, orderID)}
}

func (_c *MockPartnerClient_Handover_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockPartnerClient_Handover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartnerClient_Handover_Call) Return(err error) *MockPartnerClient_Handover_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartnerClient_Handover_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockPartnerClient_Handover_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReady provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) MarkReady(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartnerClient_MarkReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReady'
type MockPartnerClient_MarkReady_Call struct {
	*mock.Call
}

// MarkReady is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockPartnerClient_Expecter) MarkReady(ctx any, orderID any) *MockPartnerClient_MarkReady_Call {
	return &MockPartnerClient_MarkReady_Call{Call: _e.mock.On("MarkReady", ctx, orderID)}
}

func (_c *MockPartnerClient_MarkReady_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockPartnerClient_MarkReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartnerClient_MarkReady_Call) Return(err error) *MockPartnerClient_MarkReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartnerClient_MarkReady_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockPartnerClient_MarkReady_Call {
	_c.Call.Return(run)
	return _c
}

// OrderStatus provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) OrderStatus(ctx context.Context, orderID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for OrderStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartnerClient_OrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderStatus'
type MockPartnerClient_OrderStatus_Call struct {
	*mock.Call
}

// OrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockPartnerClient_Expecter) OrderStatus(ctx any, orderID any) *MockPartnerClient_OrderStatus_Call {
	return &MockPartnerClient_OrderStatus_Call{Call: _e.mock.On("OrderStatus", ctx, orderID)}
}

func (_c *MockPartnerClient_OrderStatus_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockPartnerClient_OrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartnerClient_OrderStatus_Call) Return(s string, err error) *MockPartnerClient_OrderStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPartnerClient_OrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (string, error)) *MockPartnerClient_OrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetItemAvailability provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) SetItemAvailability(ctx context.Context, sku string, available bool) error {
	ret := _mock.Called(ctx, sku, available)

	if len(ret) == 0 {
		panic("no return value specified for SetItemAvailability")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, sku, available)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartnerClient_SetItemAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetItemAvailability'
type MockPartnerClient_SetItemAvailability_Call struct {
	*mock.Call
}

// SetItemAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - available bool
func (_e *MockPartnerClient_Expecter) SetItemAvailability(ctx any, sku any, available any) *MockPartnerClient_SetItemAvailability_Call {
	return &MockPartnerClient_SetItemAvailability_Call{Call: _e.mock.On("SetItemAvailability", ctx, sku, available)}
}

func (_c *MockPartnerClient_SetItemAvailability_Call) Run(run func(ctx context.Context, sku string, available bool)) *MockPartnerClient_SetItemAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPartnerClient_SetItemAvailability_Call) Return(err error) *MockPartnerClient_SetItemAvailability_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartnerClient_SetItemAvailability_Call) RunAndReturn(run func(ctx context.Context, sku string, available bool) error) *MockPartnerClient_SetItemAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// StartCooking provides a mock function for the type MockPartnerClient
func (_mock *MockPartnerClient) StartCooking(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for StartCooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartnerClient_StartCooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCooking'
type MockPartnerClient_StartCooking_Call struct {
	*mock.Call
}

// StartCooking is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockPartnerClient_Expecter) StartCooking(ctx any, orderID any) *MockPartnerClient_StartCooking_Call {
	return &MockPartnerClient_StartCooking_Call{Call: _e.mock.On("StartCooking", ctx, orderID)}
}

func (_c *MockPartnerClient_StartCooking_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockPartnerClient_StartCooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartnerClient_StartCooking_Call) Return(err error) *MockPartnerClient_StartCooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartnerClient_StartCooking_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockPartnerClient_StartCooking_Call {
	_c.Call.Return(run)
	return _c
}
