// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/catalog"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// VenueMenu provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) VenueMenu(ctx context.Context, venueID uuid.UUID) (catalog.Menu, error) {
	ret := _mock.Called(ctx, venueID)

	if len(ret) == 0 {
		panic("no return value specified for VenueMenu")
	}

	var r0 catalog.Menu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (catalog.Menu, error)); ok {
		return returnFunc(ctx, venueID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) catalog.Menu); ok {
		r0 = returnFunc(ctx, venueID)
	} else {
		r0 = ret.Get(0).(catalog.Menu)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, venueID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_VenueMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VenueMenu'
type MockMenuRepository_VenueMenu_Call struct {
	*mock.Call
}

// VenueMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
func (_e *MockMenuRepository_Expecter) VenueMenu(ctx any, venueID any) *MockMenuRepository_VenueMenu_Call {
	return &MockMenuRepository_VenueMenu_Call{Call: _e.mock.On("VenueMenu", ctx, venueID)}
}

func (_c *MockMenuRepository_VenueMenu_Call) Run(run func(ctx context.Context, venueID uuid.UUID)) *MockMenuRepository_VenueMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMenuRepository_VenueMenu_Call) Return(menu catalog.Menu, err error) *MockMenuRepository_VenueMenu_Call {
	_c.Call.Return(menu, err)
	return _c
}

func (_c *MockMenuRepository_VenueMenu_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID) (catalog.Menu, error)) *MockMenuRepository_VenueMenu_Call {
	_c.Call.Return(run)
	return _c
}
