// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/catalog"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVenueRepository creates a new instance of MockVenueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueRepository {
	mock := &MockVenueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVenueRepository is an autogenerated mock type for the VenueRepository type
type MockVenueRepository struct {
	mock.Mock
}

type MockVenueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueRepository) EXPECT() *MockVenueRepository_Expecter {
	return &MockVenueRepository_Expecter{mock: &_m.Mock}
}

// GetVenue provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) GetVenue(ctx context.Context, id uuid.UUID) (catalog.Venue, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVenue")
	}

	var r0 catalog.Venue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (catalog.Venue, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) catalog.Venue); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(catalog.Venue)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_GetVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVenue'
type MockVenueRepository_GetVenue_Call struct {
	*mock.Call
}

// GetVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVenueRepository_Expecter) GetVenue(ctx any, id any) *MockVenueRepository_GetVenue_Call {
	return &MockVenueRepository_GetVenue_Call{Call: _e.mock.On("GetVenue", ctx, id)}
}

func (_c *MockVenueRepository_GetVenue_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVenueRepository_GetVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_GetVenue_Call) Return(venue catalog.Venue, err error) *MockVenueRepository_GetVenue_Call {
	_c.Call.Return(venue, err)
	return _c
}

func (_c *MockVenueRepository_GetVenue_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (catalog.Venue, error)) *MockVenueRepository_GetVenue_Call {
	_c.Call.Return(run)
	return _c
}

// ListCuisines provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) ListCuisines(ctx context.Context) ([]catalog.Cuisine, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCuisines")
	}

	var r0 []catalog.Cuisine
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]catalog.Cuisine, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []catalog.Cuisine); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Cuisine)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_ListCuisines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCuisines'
type MockVenueRepository_ListCuisines_Call struct {
	*mock.Call
}

// ListCuisines is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVenueRepository_Expecter) ListCuisines(ctx any) *MockVenueRepository_ListCuisines_Call {
	return &MockVenueRepository_ListCuisines_Call{Call: _e.mock.On("ListCuisines", ctx)}
}

func (_c *MockVenueRepository_ListCuisines_Call) Run(run func(ctx context.Context)) *MockVenueRepository_ListCuisines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVenueRepository_ListCuisines_Call) Return(cuisines []catalog.Cuisine, err error) *MockVenueRepository_ListCuisines_Call {
	_c.Call.Return(cuisines, err)
	return _c
}

func (_c *MockVenueRepository_ListCuisines_Call) RunAndReturn(run func(ctx context.Context) ([]catalog.Cuisine, error)) *MockVenueRepository_ListCuisines_Call {
	_c.Call.Return(run)
	return _c
}

// ListVenues provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) ListVenues(ctx context.Context, filter catalog.VenueFilter) ([]catalog.Venue, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListVenues")
	}

	var r0 []catalog.Venue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.VenueFilter) ([]catalog.Venue, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, catalog.VenueFilter) []catalog.Venue); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Venue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, catalog.VenueFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_ListVenues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVenues'
type MockVenueRepository_ListVenues_Call struct {
	*mock.Call
}

// ListVenues is a helper method to define mock.On call
//   - ctx context.Context
//   - filter catalog.VenueFilter
func (_e *MockVenueRepository_Expecter) ListVenues(ctx any, filter any) *MockVenueRepository_ListVenues_Call {
	return &MockVenueRepository_ListVenues_Call{Call: _e.mock.On("ListVenues", ctx, filter)}
}

func (_c *MockVenueRepository_ListVenues_Call) Run(run func(ctx context.Context, filter catalog.VenueFilter)) *MockVenueRepository_ListVenues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 catalog.VenueFilter
		if args[1] != nil {
			arg1 = args[1].(catalog.VenueFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_ListVenues_Call) Return(venues []catalog.Venue, err error) *MockVenueRepository_ListVenues_Call {
	_c.Call.Return(venues, err)
	return _c
}

func (_c *MockVenueRepository_ListVenues_Call) RunAndReturn(run func(ctx context.Context, filter catalog.VenueFilter) ([]catalog.Venue, error)) *MockVenueRepository_ListVenues_Call {
	_c.Call.Return(run)
	return _c
}
