// Package kitchenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package kitchenapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CartProblemType.
const (
	CartProblemTypeBelowMinimum    CartProblemType = "below_minimum"
	CartProblemTypeItemUnavailable CartProblemType = "item_unavailable"
	CartProblemTypeOutOfStock      CartProblemType = "out_of_stock"
	CartProblemTypePriceChanged    CartProblemType = "price_changed"
	CartProblemTypeVenueClosed     CartProblemType = "venue_closed"
)

// Valid indicates whether the value is a known member of the CartProblemType enum.
func (e CartProblemType) Valid() bool {
	switch e {
	case CartProblemTypeBelowMinimum:
		return true
	case CartProblemTypeItemUnavailable:
		return true
	case CartProblemTypeOutOfStock:
		return true
	case CartProblemTypePriceChanged:
		return true
	case CartProblemTypeVenueClosed:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	ACCEPTED   OrderStatus = "ACCEPTED"
	CANCELLED  OrderStatus = "CANCELLED"
	COOKING    OrderStatus = "COOKING"
	CREATED    OrderStatus = "CREATED"
	DELIVERED  OrderStatus = "DELIVERED"
	DELIVERING OrderStatus = "DELIVERING"
	READY      OrderStatus = "READY"
	REJECTED   OrderStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case CANCELLED:
		return true
	case COOKING:
		return true
	case CREATED:
		return true
	case DELIVERED:
		return true
	case DELIVERING:
		return true
	case READY:
		return true
	case REJECTED:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	UnavailableReasonOutOfStock  UnavailableReason = "out_of_stock"
	UnavailableReasonStopped     UnavailableReason = "stopped"
	UnavailableReasonVenueClosed UnavailableReason = "venue_closed"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case UnavailableReasonOutOfStock:
		return true
	case UnavailableReasonStopped:
		return true
	case UnavailableReasonVenueClosed:
		return true
	default:
		return false
	}
}

// Defines values for VenueSort.
const (
	AvgCookMinutes VenueSort = "avg_cook_minutes"
	DeliveryFee    VenueSort = "delivery_fee"
	Name           VenueSort = "name"
)

// Valid indicates whether the value is a known member of the VenueSort enum.
func (e VenueSort) Valid() bool {
	switch e {
	case AvgCookMinutes:
		return true
	case DeliveryFee:
		return true
	case Name:
		return true
	default:
		return false
	}
}

// CancelOrderRequest defines model for CancelOrderRequest.
type CancelOrderRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// Cart defines model for Cart.
type Cart struct {
	// DeliveryFee Сумма в копейках.
	DeliveryFee Money      `json:"delivery_fee"`
	Items       []CartItem `json:"items"`

	// ItemsTotal Сумма в копейках.
	ItemsTotal     Money  `json:"items_total"`
	MinOrderAmount *Money `json:"min_order_amount,omitempty"`

	// Total Сумма в копейках.
	Total Money `json:"total"`

	// VenueId Заведение корзины; `null` — корзина пуста.
	VenueId   *openapi_types.UUID `json:"venue_id,omitempty"`
	VenueName *string             `json:"venue_name,omitempty"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	ExternalId  string             `json:"external_id"`
	IsAvailable bool               `json:"is_available"`
	ItemId      openapi_types.UUID `json:"item_id"`

	// LineTotal Сумма в копейках.
	LineTotal Money  `json:"line_total"`
	Name      string `json:"name"`

	// Price Сумма в копейках.
	Price Money `json:"price"`
	Qty   int   `json:"qty"`
}

// CartProblem defines model for CartProblem.
type CartProblem struct {
	AvailableQty *int                `json:"available_qty,omitempty"`
	ItemId       *openapi_types.UUID `json:"item_id,omitempty"`
	ItemName     *string             `json:"item_name,omitempty"`
	Message      string              `json:"message"`
	NewPrice     *Money              `json:"new_price,omitempty"`

	// OldPrice Цена, по которой позиция лежала в корзине.
	OldPrice     *Money `json:"old_price,omitempty"`
	RequestedQty *int   `json:"requested_qty,omitempty"`

	// Shortfall Сколько добрать до минимальной суммы заказа.
	Shortfall *Money          `json:"shortfall,omitempty"`
	Type      CartProblemType `json:"type"`
}

// CartProblemType defines model for CartProblemType.
type CartProblemType string

// CartValidation defines model for CartValidation.
type CartValidation struct {
	// Cart Корзина, пересчитанная по актуальному меню.
	Cart Cart `json:"cart"`

	// IsValid Проблем нет, заказ можно оформлять.
	IsValid  bool          `json:"is_valid"`
	Problems []CartProblem `json:"problems"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Address string  `json:"address"`
	Comment *string `json:"comment,omitempty"`

	// ExpectedTotal Итоговая сумма, показанная пользователю.
	ExpectedTotal Money  `json:"expected_total"`
	Phone         string `json:"phone"`
}

// Cuisine defines model for Cuisine.
type Cuisine struct {
	// Name Example: Пекарня
	Name string `json:"name"`

	// Slug Example: bakery
	Slug string `json:"slug"`
}

// CuisineList defines model for CuisineList.
type CuisineList struct {
	Items []Cuisine `json:"items"`
}

// Error defines model for Error.
type Error struct {
	// Code Машиночитаемый код ошибки.
	//
	// Example: price_mismatch
	Code string `json:"code"`

	// Details Подробности, зависящие от кода.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Человекочитаемое описание.
	Message string `json:"message"`

	// TraceId Идентификатор запроса; он же в логах сервиса.
	TraceId *string `json:"trace_id,omitempty"`
}

// Menu defines model for Menu.
type Menu struct {
	Categories []MenuCategory     `json:"categories"`
	VenueId    openapi_types.UUID `json:"venue_id"`
}

// MenuCategory defines model for MenuCategory.
type MenuCategory struct {
	ExternalId string             `json:"external_id"`
	Id         openapi_types.UUID `json:"id"`
	Items      []MenuItem         `json:"items"`
	Name       string             `json:"name"`
	Position   int                `json:"position"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	Description *string `json:"description,omitempty"`

	// ExternalId Идентификатор позиции в системе заведения.
	ExternalId  string             `json:"external_id"`
	Id          openapi_types.UUID `json:"id"`
	IsAvailable bool               `json:"is_available"`
	Name        string             `json:"name"`

	// Price Сумма в копейках.
	Price Money `json:"price"`

	// StockQty Остаток; `null` — не ограничен.
	StockQty *int `json:"stock_qty,omitempty"`

	// UnavailableReason Заполнено, когда `is_available` равно `false`.
	UnavailableReason *UnavailableReason `json:"unavailable_reason,omitempty"`
}

// Money Сумма в копейках.
type Money = int64

// Order defines model for Order.
type Order struct {
	Address   *string   `json:"address,omitempty"`
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// DeliveryFee Сумма в копейках.
	DeliveryFee Money `json:"delivery_fee"`

	// EtaMinutes Оценка времени готовности, названная заведением.
	EtaMinutes *int               `json:"eta_minutes,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Items      []OrderItem        `json:"items"`

	// ItemsTotal Сумма в копейках.
	ItemsTotal Money `json:"items_total"`

	// Number Человекочитаемый номер заказа.
	//
	// Example: AK-100042
	Number          string      `json:"number"`
	Phone           string      `json:"phone"`
	RejectionReason *string     `json:"rejection_reason,omitempty"`
	Status          OrderStatus `json:"status"`

	// Total Сумма в копейках.
	Total     Money      `json:"total"`
	UpdatedAt time.Time  `json:"updated_at"`
	Venue     OrderVenue `json:"venue"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	ExternalId string `json:"external_id"`

	// LineTotal Сумма в копейках.
	LineTotal Money `json:"line_total"`

	// Name Название на момент оформления заказа.
	Name string `json:"name"`

	// Price Сумма в копейках.
	Price Money `json:"price"`
	Qty   int   `json:"qty"`
}

// OrderList defines model for OrderList.
type OrderList struct {
	Items      []Order `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderVenue defines model for OrderVenue.
type OrderVenue struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// PutCartItemRequest defines model for PutCartItemRequest.
type PutCartItemRequest struct {
	ItemId openapi_types.UUID `json:"item_id"`

	// Qty Итоговое количество; `0` удаляет позицию.
	Qty     int                `json:"qty"`
	VenueId openapi_types.UUID `json:"venue_id"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// Venue defines model for Venue.
type Venue struct {
	Address        string    `json:"address"`
	AvgCookMinutes int       `json:"avg_cook_minutes"`
	Cuisines       []Cuisine `json:"cuisines"`

	// DeliveryFee Сумма в копейках.
	DeliveryFee Money              `json:"delivery_fee"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// IsOpen Смена заведения открыта, заказы принимаются.
	IsOpen bool     `json:"is_open"`
	Lat    *float64 `json:"lat,omitempty"`
	Lon    *float64 `json:"lon,omitempty"`

	// MinOrderAmount Сумма в копейках.
	MinOrderAmount Money  `json:"min_order_amount"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
}

// VenueList defines model for VenueList.
type VenueList struct {
	Items []Venue `json:"items"`

	// NextCursor Курсор следующей страницы; `null` — страница последняя.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// VenueSort defines model for VenueSort.
type VenueSort string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// VenueId defines model for VenueId.
type VenueId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalError defines model for InternalError.
type InternalError = Error

// InvalidTransition defines model for InvalidTransition.
type InvalidTransition = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Status Фильтр по статусу; можно передать несколько значений.
	Status *[]OrderStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Курсор следующей страницы из поля `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Размер страницы.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// IdempotencyKey Уникальный ключ попытки оформления.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ListVenuesParams defines parameters for ListVenues.
type ListVenuesParams struct {
	// Q Поиск по названию заведения.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Cuisine Слаг кухни из справочника `/cuisines`.
	Cuisine *string `form:"cuisine,omitempty" json:"cuisine,omitempty"`

	// OpenNow Только заведения с открытой сменой.
	OpenNow *bool      `form:"open_now,omitempty" json:"open_now,omitempty"`
	Sort    *VenueSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Cursor Курсор следующей страницы из поля `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Размер страницы.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutCartItemJSONRequestBody defines body for PutCartItem for application/json ContentType.
type PutCartItemJSONRequestBody = PutCartItemRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// CancelOrderJSONRequestBody defines body for CancelOrder for application/json ContentType.
type CancelOrderJSONRequestBody = CancelOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ClearCart Очистить корзину
	// (DELETE /cart)
	ClearCart(w http.ResponseWriter, r *http.Request)
	// GetCart Текущая корзина
	// (GET /cart)
	GetCart(w http.ResponseWriter, r *http.Request)
	// PutCartItem Задать количество позиции в корзине
	// (PUT /cart/items)
	PutCartItem(w http.ResponseWriter, r *http.Request)
	// DeleteCartItem Удалить позицию из корзины
	// (DELETE /cart/items/{item_id})
	DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// ValidateCart Проверить корзину перед оформлением
	// (POST /cart/validate)
	ValidateCart(w http.ResponseWriter, r *http.Request)
	// ListCuisines Справочник кухонь
	// (GET /cuisines)
	ListCuisines(w http.ResponseWriter, r *http.Request)
	// ListOrders Заказы пользователя
	// (GET /orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// CreateOrder Оформить заказ
	// (POST /orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetOrder Карточка заказа
	// (GET /orders/{order_id})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// CancelOrder Отменить заказ
	// (POST /orders/{order_id}/cancel)
	CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// ListVenues Список заведений
	// (GET /venues)
	ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams)
	// GetVenue Карточка заведения
	// (GET /venues/{venue_id})
	GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId)
	// GetVenueMenu Меню заведения
	// (GET /venues/{venue_id}/menu)
	GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ClearCart Очистить корзину
// (DELETE /cart)
func (_ Unimplemented) ClearCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCart Текущая корзина
// (GET /cart)
func (_ Unimplemented) GetCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PutCartItem Задать количество позиции в корзине
// (PUT /cart/items)
func (_ Unimplemented) PutCartItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCartItem Удалить позицию из корзины
// (DELETE /cart/items/{item_id})
func (_ Unimplemented) DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ValidateCart Проверить корзину перед оформлением
// (POST /cart/validate)
func (_ Unimplemented) ValidateCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCuisines Справочник кухонь
// (GET /cuisines)
func (_ Unimplemented) ListCuisines(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListOrders Заказы пользователя
// (GET /orders)
func (_ Unimplemented) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrder Оформить заказ
// (POST /orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetOrder Карточка заказа
// (GET /orders/{order_id})
func (_ Unimplemented) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelOrder Отменить заказ
// (POST /orders/{order_id}/cancel)
func (_ Unimplemented) CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVenues Список заведений
// (GET /venues)
func (_ Unimplemented) ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVenue Карточка заведения
// (GET /venues/{venue_id})
func (_ Unimplemented) GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVenueMenu Меню заведения
// (GET /venues/{venue_id}/menu)
func (_ Unimplemented) GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ClearCart operation middleware
func (siw *ServerInterfaceWrapper) ClearCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCart operation middleware
func (siw *ServerInterfaceWrapper) GetCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutCartItem operation middleware
func (siw *ServerInterfaceWrapper) PutCartItem(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutCartItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCartItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCartItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateCart operation middleware
func (siw *ServerInterfaceWrapper) ValidateCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCuisines operation middleware
func (siw *ServerInterfaceWrapper) ListCuisines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCuisines(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelOrder operation middleware
func (siw *ServerInterfaceWrapper) CancelOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVenues operation middleware
func (siw *ServerInterfaceWrapper) ListVenues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVenuesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cuisine" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cuisine", r.URL.Query(), &params.Cuisine, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cuisine"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cuisine", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "open_now" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "open_now", r.URL.Query(), &params.OpenNow, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "open_now"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "open_now", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVenues(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenue operation middleware
func (siw *ServerInterfaceWrapper) GetVenue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venue_id" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venue_id", chi.URLParam(r, "venue_id"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venue_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenue(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenueMenu operation middleware
func (siw *ServerInterfaceWrapper) GetVenueMenu(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venue_id" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venue_id", chi.URLParam(r, "venue_id"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venue_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenueMenu(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cuisines", wrapper.ListCuisines)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues", wrapper.ListVenues)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues/{venue_id}", wrapper.GetVenue)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues/{venue_id}/menu", wrapper.GetVenueMenu)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cart", wrapper.ClearCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cart", wrapper.GetCart)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/cart/items", wrapper.PutCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cart/items/{item_id}", wrapper.DeleteCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cart/validate", wrapper.ValidateCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders", wrapper.ListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{order_id}", wrapper.GetOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders/{order_id}/cancel", wrapper.CancelOrder)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type InternalErrorJSONResponse Error

type InvalidTransitionJSONResponse Error

type NotFoundJSONResponse Error

type ClearCartRequestObject struct {
}

type ClearCartResponseObject interface {
	VisitClearCartResponse(w http.ResponseWriter) error
}

type ClearCart204Response struct {
}

func (response ClearCart204Response) VisitClearCartResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ClearCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response ClearCart500JSONResponse) VisitClearCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCartRequestObject struct {
}

type GetCartResponseObject interface {
	VisitGetCartResponse(w http.ResponseWriter) error
}

type GetCart200JSONResponse Cart

func (response GetCart200JSONResponse) VisitGetCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetCart500JSONResponse) VisitGetCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItemRequestObject struct {
	Body *PutCartItemJSONRequestBody
}

type PutCartItemResponseObject interface {
	VisitPutCartItemResponse(w http.ResponseWriter) error
}

type PutCartItem200JSONResponse Cart

func (response PutCartItem200JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem400JSONResponse struct{ BadRequestJSONResponse }

func (response PutCartItem400JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem404JSONResponse struct{ NotFoundJSONResponse }

func (response PutCartItem404JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem409JSONResponse struct{ ConflictJSONResponse }

func (response PutCartItem409JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem500JSONResponse struct{ InternalErrorJSONResponse }

func (response PutCartItem500JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItemRequestObject struct {
	ItemId openapi_types.UUID `json:"item_id"`
}

type DeleteCartItemResponseObject interface {
	VisitDeleteCartItemResponse(w http.ResponseWriter) error
}

type DeleteCartItem200JSONResponse Cart

func (response DeleteCartItem200JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItem404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCartItem404JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItem500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteCartItem500JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateCartRequestObject struct {
}

type ValidateCartResponseObject interface {
	VisitValidateCartResponse(w http.ResponseWriter) error
}

type ValidateCart200JSONResponse CartValidation

func (response ValidateCart200JSONResponse) VisitValidateCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response ValidateCart500JSONResponse) VisitValidateCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCuisinesRequestObject struct {
}

type ListCuisinesResponseObject interface {
	VisitListCuisinesResponse(w http.ResponseWriter) error
}

type ListCuisines200JSONResponse CuisineList

func (response ListCuisines200JSONResponse) VisitListCuisinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCuisines500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListCuisines500JSONResponse) VisitListCuisinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrdersRequestObject struct {
	Params ListOrdersParams
}

type ListOrdersResponseObject interface {
	VisitListOrdersResponse(w http.ResponseWriter) error
}

type ListOrders200JSONResponse OrderList

func (response ListOrders200JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response ListOrders400JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrders500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListOrders500JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Params CreateOrderParams
	Body   *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder200JSONResponse Order

func (response CreateOrder200JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409JSONResponse Error

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder422JSONResponse Error

func (response CreateOrder422JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse Order

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetOrder500JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
	Body    *CancelOrderJSONRequestBody
}

type CancelOrderResponseObject interface {
	VisitCancelOrderResponse(w http.ResponseWriter) error
}

type CancelOrder200JSONResponse Order

func (response CancelOrder200JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelOrder404JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder409JSONResponse struct{ InvalidTransitionJSONResponse }

func (response CancelOrder409JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response CancelOrder500JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenuesRequestObject struct {
	Params ListVenuesParams
}

type ListVenuesResponseObject interface {
	VisitListVenuesResponse(w http.ResponseWriter) error
}

type ListVenues200JSONResponse VenueList

func (response ListVenues200JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenues400JSONResponse struct{ BadRequestJSONResponse }

func (response ListVenues400JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenues500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVenues500JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueRequestObject struct {
	VenueId VenueId `json:"venue_id"`
}

type GetVenueResponseObject interface {
	VisitGetVenueResponse(w http.ResponseWriter) error
}

type GetVenue200JSONResponse Venue

func (response GetVenue200JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenue404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVenue404JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenue500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVenue500JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenuRequestObject struct {
	VenueId VenueId `json:"venue_id"`
}

type GetVenueMenuResponseObject interface {
	VisitGetVenueMenuResponse(w http.ResponseWriter) error
}

type GetVenueMenu200JSONResponse Menu

func (response GetVenueMenu200JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenu404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVenueMenu404JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenu500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVenueMenu500JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ClearCart Очистить корзину
	// (DELETE /cart)
	ClearCart(ctx context.Context, request ClearCartRequestObject) (ClearCartResponseObject, error)
	// GetCart Текущая корзина
	// (GET /cart)
	GetCart(ctx context.Context, request GetCartRequestObject) (GetCartResponseObject, error)
	// PutCartItem Задать количество позиции в корзине
	// (PUT /cart/items)
	PutCartItem(ctx context.Context, request PutCartItemRequestObject) (PutCartItemResponseObject, error)
	// DeleteCartItem Удалить позицию из корзины
	// (DELETE /cart/items/{item_id})
	DeleteCartItem(ctx context.Context, request DeleteCartItemRequestObject) (DeleteCartItemResponseObject, error)
	// ValidateCart Проверить корзину перед оформлением
	// (POST /cart/validate)
	ValidateCart(ctx context.Context, request ValidateCartRequestObject) (ValidateCartResponseObject, error)
	// ListCuisines Справочник кухонь
	// (GET /cuisines)
	ListCuisines(ctx context.Context, request ListCuisinesRequestObject) (ListCuisinesResponseObject, error)
	// ListOrders Заказы пользователя
	// (GET /orders)
	ListOrders(ctx context.Context, request ListOrdersRequestObject) (ListOrdersResponseObject, error)
	// CreateOrder Оформить заказ
	// (POST /orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// GetOrder Карточка заказа
	// (GET /orders/{order_id})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// CancelOrder Отменить заказ
	// (POST /orders/{order_id}/cancel)
	CancelOrder(ctx context.Context, request CancelOrderRequestObject) (CancelOrderResponseObject, error)
	// ListVenues Список заведений
	// (GET /venues)
	ListVenues(ctx context.Context, request ListVenuesRequestObject) (ListVenuesResponseObject, error)
	// GetVenue Карточка заведения
	// (GET /venues/{venue_id})
	GetVenue(ctx context.Context, request GetVenueRequestObject) (GetVenueResponseObject, error)
	// GetVenueMenu Меню заведения
	// (GET /venues/{venue_id}/menu)
	GetVenueMenu(ctx context.Context, request GetVenueMenuRequestObject) (GetVenueMenuResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ClearCart operation middleware
func (sh *strictHandler) ClearCart(w http.ResponseWriter, r *http.Request) {
	var request ClearCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClearCart(ctx, request.(ClearCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClearCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClearCartResponseObject); ok {
		if err := validResponse.VisitClearCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCart operation middleware
func (sh *strictHandler) GetCart(w http.ResponseWriter, r *http.Request) {
	var request GetCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCart(ctx, request.(GetCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCartResponseObject); ok {
		if err := validResponse.VisitGetCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutCartItem operation middleware
func (sh *strictHandler) PutCartItem(w http.ResponseWriter, r *http.Request) {
	var request PutCartItemRequestObject

	var body PutCartItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutCartItem(ctx, request.(PutCartItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutCartItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutCartItemResponseObject); ok {
		if err := validResponse.VisitPutCartItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCartItem operation middleware
func (sh *strictHandler) DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	var request DeleteCartItemRequestObject

	request.ItemId = itemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCartItem(ctx, request.(DeleteCartItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCartItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCartItemResponseObject); ok {
		if err := validResponse.VisitDeleteCartItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidateCart operation middleware
func (sh *strictHandler) ValidateCart(w http.ResponseWriter, r *http.Request) {
	var request ValidateCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidateCart(ctx, request.(ValidateCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidateCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidateCartResponseObject); ok {
		if err := validResponse.VisitValidateCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCuisines operation middleware
func (sh *strictHandler) ListCuisines(w http.ResponseWriter, r *http.Request) {
	var request ListCuisinesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCuisines(ctx, request.(ListCuisinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCuisines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCuisinesResponseObject); ok {
		if err := validResponse.VisitListCuisinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrders operation middleware
func (sh *strictHandler) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	var request ListOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrders(ctx, request.(ListOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrdersResponseObject); ok {
		if err := validResponse.VisitListOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	var request CreateOrderRequestObject

	request.Params = params

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelOrder operation middleware
func (sh *strictHandler) CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request CancelOrderRequestObject

	request.OrderId = orderId

	var body CancelOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelOrder(ctx, request.(CancelOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelOrderResponseObject); ok {
		if err := validResponse.VisitCancelOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVenues operation middleware
func (sh *strictHandler) ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams) {
	var request ListVenuesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVenues(ctx, request.(ListVenuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVenues")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVenuesResponseObject); ok {
		if err := validResponse.VisitListVenuesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVenue operation middleware
func (sh *strictHandler) GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	var request GetVenueRequestObject

	request.VenueId = venueId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVenue(ctx, request.(GetVenueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVenue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVenueResponseObject); ok {
		if err := validResponse.VisitGetVenueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVenueMenu operation middleware
func (sh *strictHandler) GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	var request GetVenueMenuRequestObject

	request.VenueId = venueId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVenueMenu(ctx, request.(GetVenueMenuRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVenueMenu")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVenueMenuResponseObject); ok {
		if err := validResponse.VisitGetVenueMenuResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Hxtb9tIkv9XIfj/v2RkxZM9YJRXWcc38E1mEiSZ4A5xIDJS2+aORCok5YlhGPDDJk7gXLxZLDCLwe7O",
	"0+H2rUa2YtmWlK/Q/RXukxyquptsik092HJm7lWsiN2s7vpV1a+qq7VpVvx6w/eIF4VmadNsOIFTJxEJ",
	"8NNCMwj9AP6qkrASuI3I9T2zZNLv2B7bZjt0wLYNtkPPaYcesz32lr2mHXpqsB22y7Zpi/Zpl71kBwbt",
	"0hODfqADes4ODdsjz6NyBSe3C6ZlujDpsyYJNkzL9Jw6MUsm/9q0zLCyRuoOCBFtNOCbMApcb9Xc2rLM",
	"O27djTTy/UBb9IT2aAflSwuT98IazqW+r0pWnGYtMkvzRcusO8/derNulq4X4ZPriU+WFMv1IrJKApTr",
	"blAlwVIVJsFXNZxoLXmTD9+W3appmQF51nQDUjVLUdAk6stX/KDuRGbJbDbxyeziHxGvSXJfsg7fXvYl",
	"WzA4bPheSBAQv3eq98mzJglx0yu+FxEP/3QajZpbcWD/5/4QghI2ldf8/4CsmCXz/80lYJvj34Zzi0Hg",
	"B/xVQ0r8lrboB7ZNB2zHoH3aMcSnV+wdPTdom7boOe3SY9piL2mXvTW3LHPB91ZqbuVjiPcXgDqAi7Zp",
	"N5Ful3ZpGwyDdtg+7bJdg+3SDj1je2gcPbZnoOHAwAE7RFSi6EteRALPqfE3Xr38f6Z9toem0aF92meH",
	"7NCA3aVd+gs9oy0u07pTc6sPA8cLXT7wyuX6HqyWdtgLOqDHBj0RKOiw1+wd7XNXktrSIzpAI6cttsv2",
	"2A5t8VFn6ARwHV/60b/6Ta/6EcT/gXbYDnePArV92qKn9Bi2uWDQf7I9+p4O6KkiJKwH/nwPjwOEANPv",
	"2C7bAZ3AI2eGLddgF5Y9tH8hCzpqx6uQGnodxT4bgd8gQeRy2w2II5ZYd57fId5qtGaWfgfOLOtaxP/4",
	"T/9AKhHalRNopqySmrtOgo3yCiHjduwL3yMbMJUbkTqOjv8YNQxevBSRuplI5QSBk8xUjvzIqU389rrr",
	"lbn/dep+U8CgVru7YpYeTzTFE8v0mrWa87RGuD8FwaYSIfbM2bgFLq8NwRRtEr3KGfqSE9qlfXZw07Dh",
	"5bbxP9t/SX0FmP8A4AckQYQb9uxpmTM6l1Lx4LE57vEtNag8FppMK8RKo0Nu0pMccKGOMwAjz7lPFLuV",
	"EdoNy8664wpR4wee+n6NOJ7EiBg9JthZZs31yJRwkvuVmasRuJXJbeJZtIGGOZpVDG85j+7qHgmB5Ov5",
	"xKmFDe1ZnjruBf7Tmk4j8dCykDkHKbHcI1UwFpU4dkJQWmadhKGzqleIR74px0q5tMX7terFZxsy+v9G",
	"Y29ZSJC5Ve+iZWOQANJ8AsyVdiEYANV+j8ynZdB22gd0CqZG1IAHBFKdXGPhmh9EK06tNoPV/Qgi0nP2",
	"Bv416DEd0F+AjrNd9gY/GrSH0ndpD9bF3tA+rhyiKO3RHqQPSjjXrpEvYXwkEbB+CI8PWxTOkWBojGU8",
	"FG8kHtjrY25w5cqa460SQLbfjMr+SjmM/MrXwjOWm15ieNLhVmp+iAOekpr/TVl6gCcadMPbHwEdcyQT",
	"S5tmRcToyRSGEV2jr+/UoIKY5HRsh7NZzKP6tAVYRLi26BnQLkV1QHEh96J99rYgvDTSSE3A+x5h/gvC",
	"uod8ie1aKjOiPTqg72FeYEZ/ROF6kEUCfgqJF1dcfoNraDqOIR1ehmYM+125FuU9Ft96LWIC4kRkNDFz",
	"qtWAhKGOmdVdT36+rkFExa/XBZUdw+kgTDRIBbxAHOAuadh/BS8F5BsyMXYY26v0ZNJgU3hBkJyIMUDi",
	"zwVGGmu+R4YW8sn8mB0Y0o3cSDlbZtFaDTXd0OWvTqtFRh3y3Kk3wNdgagKrYtuQLukYRFhrrqbHPHW+",
	"5lWG0aLjQBG9R0h5x9UBaEpGLRY8Fuk4mU6YOEMd8j9+lWhM/G+0hUllnw5iFwJ58AFEtzOe5CVpZ7eA",
	"apPbx91q3Q3rTlRZ0215lUSOW5OGhEmqU7unCMaDXCbJHNBj4Xv6IhvvCsfTpl1IvNhrTsAHbFfIyYNP",
	"ZjsU1jH0ln8CwBHsHQzUyvLpAOemH+BlvDjF43dmgVHgVHLShb/yRAFkZ3+kXcQmUockbR7A7DfhTX2D",
	"55dtA2U6oi32wmA76N7bXIrCWJyijkcHyS+I19QFp4is+sEwYkd6HuI1F/iwDV36p+ZR46tl6iqU2pgi",
	"V95iYhmmT08myzums18QKS8jzk9H/KR+My6zyE8q5CTWCOcQi6epFijg3dRFqNRuTo51hSLTLgCc7aAJ",
	"76KhdaRVx2k1O9Qa2qTaGptzzigpRO4oSfvQbvxDFrwgzqarAn3uWI7imvc+Vp7ysy2F+CsMtZzUiyYj",
	"Cl8lY+/zoRrSgDVdoAEgJnhei/vWI/Cuhq3urW3gCtrI/ewVpxYSW0P+J0evSInH5r9cAdk9/1HyG5l4",
	"ATemp4jEF6mai+tF/3LDVE4JirrNRlY4kg6OTXgVApj9DqlntexEKVhXnYhci1zcEk0wvUBBj0QO5C3N",
	"SGPmgNSXqOkz3DesNve4GRpAHhHB7VQM7iNvbKvM8WS4LkZ7kwH6SjwwP92ZYVHSa9afkmA6AsH5E+Zb",
	"eMw1nCMnHOrW59euF4vFG/O6lce8O/NNQMAgXN9TPMFYQIaREzUn28AH/NGpy6fNRnVqXGPAn0gqPFTT",
	"x0ShJTlbvFhrmvpnkpso9plalM4lJYibmoNcoqg5BMa/K3bZFQcbPD/nyf5uKkOXoTYDzNmUSseQmOmK",
	"orlbPot8i7t5HVlLTsEvWnLPFfxBbIeyQLVwf/HWw8XbpmXeWlhYvMf/XLh79/OlLz8zLfP+4q3b/2Fa",
	"5u3FO0uPFu/z/xQf8NH7i/+2uCBG3fpyYfHOncXb2jKVYkbZnZvMHecQKK1R5mXM95qRPFfIrbxMczig",
	"52FqEWQgjmvoOSdd4mx4cNOwi7bB9oDi0HN2SDtgKmpd9y3YRU6DgZY6zCT1SY4QYG26PcxSOgVQYeQ3",
	"GrpaZ6qwqUNIDjgU4pMZ4qyvliu+/7VKNLLbUuGljRnUQi5IhcalOJOnGH6DeDoOKshTS5PU8KPjM7bN",
	"DoAkqGVUdsDbE+I6O3vLT5f1FdTacGz1m7xmneOjRGSEkXzhFxipO5i93BGcLMZN4EXU8pul1BFjQCU6",
	"0UiaCfUZtOqMC61gFgFGUJaxAeZyPVypJDP9JR4+Y6UJJ+G9JIXxx3sThzRc4QM/iFJdWVJd0iGJj5Pr",
	"QpEjJJVm4EYbD2BPuRK+CmUL13SViGyF+9Ayvvpq6XbceLZGnCoSSdGq9e/X4F3XlhRf4DTczwHeIJvr",
	"rfhZMW7dWzLQ/n+5Rs+wEYrLhLo4pwP2mrboMT2j3ZIhRGzxwl82nTq1hpoJhn1HlysYqw3LXqrZZgDJ",
	"sErxlr1lD+ur2Y14Y2C/lrJ5GP622R7ERN7tAlMdYRCFkRBOe4Yd75BdMOif2B7Ol9bAy5hsLnsIzR5K",
	"1KNd44tH90qGcoDVoT3LYPuwnIxAKW2Cx5TtZlgGbrMD9kpE9gGWiEX70St6zt4my/8z2wEywPe3Q9/T",
	"PjvA2ivmc8AOsJ2D29JLkeR1DJQQrGiQ1Bc69KywDG4nciN+CvEnLNfu0kEBbfgF2JtsCIlxwHZA9fTU",
	"uHVvCWNyEHLcXC8UC0UwKvBmTsM1S+YnhWLhE+DHTrSG0J+TR4lVUiMReldwT3juCCZhLtSIE+AJ4lCD",
	"4Hzxhs7VpBtVeB77mgcyEOV3xWKek4tnn0v3x6HRNut1J9jgVYZ9UfLr8oNltW1mD3bPWQ2xgI0ndVuW",
	"uUqi7Lo+I5F+VcWZdY7xc1dN49jQJuW4kpsG2+Npf5sTz9wnOSTipiB2OJud/inuvGvx5jRF6uw+b1kc",
	"THNxJGs0dQ27P3MhsfbTRhRDnolEuTsBxS4Y9rNoo2SM5dncOofaJngSewRuJW6w4ChKV5ZRkLiTYQCR",
	"TuogQ8ZKmc6NY/RzR3zEsqfjb+hwsIIb620gTskUaUGv9o3ipwZsbFmwbdH3anNfkUa1kgqZcT/I7/3q",
	"xsxArUm2ttLhPW5G+dhm9X1+/0Iau1uWeWMS61B6oHHIjfFD4vZTHPDp+AFxG/NMTPZbZAKt2DEOW4/m",
	"BCUNuXF2PbcpcsmtUUHjNv6/gkT1ssHjSxz4xL0mlq4RPklzL94H/+S3j9wpYXh5VP3M/awMuCk/Ky58",
	"pHpXR4BonXc18ZqAH0baxLcN2yG9eiq8G2xH7Qjv0l6mxZ63FwmgIJ/VuF9APq6ijQ1qr3kEAr4rjukH",
	"9Ey0+cuWpYJBv0tIl4HNbYe86wXZIi+Y8h3qsHdxOxU9Nth/Qq6OWgWOq6udlpY9+97dBw+NOcw3Qzsn",
	"ROB6uYhn8U2EpKtKLJVts1eorZ10p/+Anuqihmg1Ix+DECltbTk99fSE7UHs5ZmHXCKuCojuzaFFY8FD",
	"2I8k1R2k3LRt2LJzy56NJXyvyKKjn6rWs2oGcXNsQylnCbqaOU4Fh7CfQPgYmR/6S9wsAJhhi4lscTau",
	"ICWTCRYyOLjjhtFCUge5OhwoLU46EPyIGm7h5Zp9FPbMQIt/QQe0z97MRpdj36JqKnJq/qpQFrdQRVXZ",
	"XbzLHxkX+P4rUR7vsVTzbbZ3M9UTGSNLepk+RIx0z+2JihKuYvK8UcN2LR4Jdffh4tOtRH2Tn3coh3tD",
	"PWb6wcmOzIlLhxM8yW//XWlwTk6BtJAcqoIptpW6gzSgbUskbVgHYDvCH79gexfknbNhhUlxWJ9DKmgX",
	"+H7Cm4n0IRpip7i6lOrhzVzZOh3iBhh7ZVlA5H0d9q5g8OZ48YDaGNCVDaWSB54ue6JmggUlWeA2UuUp",
	"2Pk+dsa9EuWsXlKvaou2+z4/Wlc66GKC0eM9dPZSldQbfkS8ysa1z8mGrSUOhj1fLNoguQBJh3aWPXm/",
	"C+/c4YsGyMI7bLdg0J94nek9z3PP2Vu2Dy+Pk0fkNruiYNQTqeD8/LLnJhKVvyYb5YA0Q2Lj4ux0F2xc",
	"wU26deMrB7BveWB4Y+BFR4gU5/zsV2EwncKyR3+gLbaDjvK9coMJ9m4bv9kHYEi6wtsOOxigYtBgWpvu",
	"+dRmtEpb9Vh3+jP34rJBXfad8r3FtX7AA5MzjsEMCcst2w6B4PIJxuzzck37+UfOy8Xpt8Z5/kPC3kgK",
	"Xm1t+ypCaI8bRRd9bAqfwpJ6sVYBYuAj54vXP8I6vlWdi/CAtH/hcsKnH+lmtXDNfR6OYrlLwI5T9mcZ",
	"tnrAa1vLnj18nQUeUo99+R1Vy7wxP3/1y7FTV2f0dyOPaYe9oh2sLXamvHF0E1xovRFtlIGb2zcNO9fZ",
	"zqqYLZ2QyCZiYTTx2DKfX4vliZKmSEFI5zblrw1s5XLTz0iU40rHEDD5MwdXT8FyKuYtto0eY3+Ycf1a",
	"RZGRImnIlFZRcxW8zj2iGgK+M24E4NRD5gTK7RtN32RyJZ3t8/NAtQsT4VbifM0WDUNAYJY9WzYN2QUj",
	"TZZ4QWqgCCRddfx/7B1WrpRSudiREbRJG/WTW+6XhOoVRNrsDfyt7O9nfBy7UNx7SgdXV6/O/k7EjByh",
	"RNUEjjDHlsi6+G0b+Bpj1Ogk/RF/ZByrBBvATE9cg0znJm9z7hzo8uxnqRRbuf52fewNQMiRM0nYOW3R",
	"I1mzwDbrLucmmcIGbRl2XGQa8UM8vEdq5C/xZOT4KV2AGK61Qk6jdivx8CuUPeA1Cp0wfoN4Zc//RidN",
	"3MAE4mgrGn6Q/oGfsV012HPyf65okXQWXaxokSoI/mr1iR/VontWrLw6HDfxuU3Z6DiS9jwSndzTxRL5",
	"w0tXr8TJaU/KvH5L5Cct2MRam6uLa4T6wvffcVY84mF79IPsrxk6GByIyqlaC2qzAyw37PPSROrKUcng",
	"14yQ8vAcVLmrxJNMO3tHSktWJLrwOuRvEmEomQ5gf5PHZOL3KHgF6Aj5Xpcd8uT6V8BXLNeEuFL6+nDT",
	"ZUff4yewryEJ1qU6mkHNLJlzTsOdW7+Ouy6m29QZ36hOOkM5kFZiqBBKEygna/tRp4KQZG3mkj5RLO3i",
	"7V7l4OBg6AfoQnPrydb/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
