// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/cart"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Cart provides a mock function for the type MockRepository
func (_mock *MockRepository) Cart(ctx context.Context, userID uuid.UUID) (cart.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Cart")
	}

	var r0 cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (cart.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) cart.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(cart.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Cart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cart'
type MockRepository_Cart_Call struct {
	*mock.Call
}

// Cart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) Cart(ctx any, userID any) *MockRepository_Cart_Call {
	return &MockRepository_Cart_Call{Call: _e.mock.On("Cart", ctx, userID)}
}

func (_c *MockRepository_Cart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_Cart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Cart_Call) Return(cart1 cart.Cart, err error) *MockRepository_Cart_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *MockRepository_Cart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (cart.Cart, error)) *MockRepository_Cart_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type MockRepository
func (_mock *MockRepository) Clear(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) Clear(ctx any, userID any) *MockRepository_Clear_Call {
	return &MockRepository_Clear_Call{Call: _e.mock.On("Clear", ctx, userID)}
}

func (_c *MockRepository_Clear_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Clear_Call) Return(err error) *MockRepository_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Clear_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockRepository_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveItem(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userID, itemID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockRepository_Expecter) RemoveItem(ctx any, userID any, itemID any) *MockRepository_RemoveItem_Call {
	return &MockRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, userID, itemID)}
}

func (_c *MockRepository_RemoveItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID)) *MockRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveItem_Call) Return(b bool, err error) *MockRepository_RemoveItem_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_RemoveItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) (bool, error)) *MockRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// SetItem provides a mock function for the type MockRepository
func (_mock *MockRepository) SetItem(ctx context.Context, userID uuid.UUID, venueID uuid.UUID, itemID uuid.UUID, qty int, price int64) error {
	ret := _mock.Called(ctx, userID, venueID, itemID, qty, price)

	if len(ret) == 0 {
		panic("no return value specified for SetItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int, int64) error); ok {
		r0 = returnFunc(ctx, userID, venueID, itemID, qty, price)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetItem'
type MockRepository_SetItem_Call struct {
	*mock.Call
}

// SetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - venueID uuid.UUID
//   - itemID uuid.UUID
//   - qty int
//   - price int64
func (_e *MockRepository_Expecter) SetItem(ctx any, userID any, venueID any, itemID any, qty any, price any) *MockRepository_SetItem_Call {
	return &MockRepository_SetItem_Call{Call: _e.mock.On("SetItem", ctx, userID, venueID, itemID, qty, price)}
}

func (_c *MockRepository_SetItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, venueID uuid.UUID, itemID uuid.UUID, qty int, price int64)) *MockRepository_SetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_SetItem_Call) Return(err error) *MockRepository_SetItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, venueID uuid.UUID, itemID uuid.UUID, qty int, price int64) error) *MockRepository_SetItem_Call {
	_c.Call.Return(run)
	return _c
}
