// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/platform/idempotency"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockStore
func (_mock *MockStore) Complete(ctx context.Context, key idempotency.Key, status int, body []byte) error {
	ret := _mock.Called(ctx, key, status, body)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, idempotency.Key, int, []byte) error); ok {
		r0 = returnFunc(ctx, key, status, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockStore_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - key idempotency.Key
//   - status int
//   - body []byte
func (_e *MockStore_Expecter) Complete(ctx any, key any, status any, body any) *MockStore_Complete_Call {
	return &MockStore_Complete_Call{Call: _e.mock.On("Complete", ctx, key, status, body)}
}

func (_c *MockStore_Complete_Call) Run(run func(ctx context.Context, key idempotency.Key, status int, body []byte)) *MockStore_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 idempotency.Key
		if args[1] != nil {
			arg1 = args[1].(idempotency.Key)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Complete_Call) Return(err error) *MockStore_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Complete_Call) RunAndReturn(run func(ctx context.Context, key idempotency.Key, status int, body []byte) error) *MockStore_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockStore
func (_mock *MockStore) Reserve(ctx context.Context, key idempotency.Key, record idempotency.Record, expires time.Time) (*idempotency.Record, error) {
	ret := _mock.Called(ctx, key, record, expires)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 *idempotency.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, idempotency.Key, idempotency.Record, time.Time) (*idempotency.Record, error)); ok {
		return returnFunc(ctx, key, record, expires)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, idempotency.Key, idempotency.Record, time.Time) *idempotency.Record); ok {
		r0 = returnFunc(ctx, key, record, expires)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idempotency.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, idempotency.Key, idempotency.Record, time.Time) error); ok {
		r1 = returnFunc(ctx, key, record, expires)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockStore_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - key idempotency.Key
//   - record idempotency.Record
//   - expires time.Time
func (_e *MockStore_Expecter) Reserve(ctx any, key any, record any, expires any) *MockStore_Reserve_Call {
	return &MockStore_Reserve_Call{Call: _e.mock.On("Reserve", ctx, key, record, expires)}
}

func (_c *MockStore_Reserve_Call) Run(run func(ctx context.Context, key idempotency.Key, record idempotency.Record, expires time.Time)) *MockStore_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 idempotency.Key
		if args[1] != nil {
			arg1 = args[1].(idempotency.Key)
		}
		var arg2 idempotency.Record
		if args[2] != nil {
			arg2 = args[2].(idempotency.Record)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Reserve_Call) Return(record1 *idempotency.Record, err error) *MockStore_Reserve_Call {
	_c.Call.Return(record1, err)
	return _c
}

func (_c *MockStore_Reserve_Call) RunAndReturn(run func(ctx context.Context, key idempotency.Key, record idempotency.Record, expires time.Time) (*idempotency.Record, error)) *MockStore_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
