// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInbox creates a new instance of MockInbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInbox {
	mock := &MockInbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInbox is an autogenerated mock type for the Inbox type
type MockInbox struct {
	mock.Mock
}

type MockInbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInbox) EXPECT() *MockInbox_Expecter {
	return &MockInbox_Expecter{mock: &_m.Mock}
}

// Remember provides a mock function for the type MockInbox
func (_mock *MockInbox) Remember(ctx context.Context, consumer string, eventID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, consumer, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Remember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, consumer, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, consumer, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, consumer, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInbox_Remember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remember'
type MockInbox_Remember_Call struct {
	*mock.Call
}

// Remember is a helper method to define mock.On call
//   - ctx context.Context
//   - consumer string
//   - eventID uuid.UUID
func (_e *MockInbox_Expecter) Remember(ctx any, consumer any, eventID any) *MockInbox_Remember_Call {
	return &MockInbox_Remember_Call{Call: _e.mock.On("Remember", ctx, consumer, eventID)}
}

func (_c *MockInbox_Remember_Call) Run(run func(ctx context.Context, consumer string, eventID uuid.UUID)) *MockInbox_Remember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInbox_Remember_Call) Return(b bool, err error) *MockInbox_Remember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockInbox_Remember_Call) RunAndReturn(run func(ctx context.Context, consumer string, eventID uuid.UUID) (bool, error)) *MockInbox_Remember_Call {
	_c.Call.Return(run)
	return _c
}
