// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/venue/internal/kitchen"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKitchen creates a new instance of MockKitchen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKitchen(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKitchen {
	mock := &MockKitchen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKitchen is an autogenerated mock type for the Kitchen type
type MockKitchen struct {
	mock.Mock
}

type MockKitchen_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKitchen) EXPECT() *MockKitchen_Expecter {
	return &MockKitchen_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockKitchen
func (_mock *MockKitchen) Cancel(ctx context.Context, cancelled kitchen.OrderCancelled) error {
	ret := _mock.Called(ctx, cancelled)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kitchen.OrderCancelled) error); ok {
		r0 = returnFunc(ctx, cancelled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKitchen_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockKitchen_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - cancelled kitchen.OrderCancelled
func (_e *MockKitchen_Expecter) Cancel(ctx any, cancelled any) *MockKitchen_Cancel_Call {
	return &MockKitchen_Cancel_Call{Call: _e.mock.On("Cancel", ctx, cancelled)}
}

func (_c *MockKitchen_Cancel_Call) Run(run func(ctx context.Context, cancelled kitchen.OrderCancelled)) *MockKitchen_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kitchen.OrderCancelled
		if args[1] != nil {
			arg1 = args[1].(kitchen.OrderCancelled)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKitchen_Cancel_Call) Return(err error) *MockKitchen_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKitchen_Cancel_Call) RunAndReturn(run func(ctx context.Context, cancelled kitchen.OrderCancelled) error) *MockKitchen_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockKitchen
func (_mock *MockKitchen) Receive(ctx context.Context, placed kitchen.OrderCreated) error {
	ret := _mock.Called(ctx, placed)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kitchen.OrderCreated) error); ok {
		r0 = returnFunc(ctx, placed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKitchen_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockKitchen_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - placed kitchen.OrderCreated
func (_e *MockKitchen_Expecter) Receive(ctx any, placed any) *MockKitchen_Receive_Call {
	return &MockKitchen_Receive_Call{Call: _e.mock.On("Receive", ctx, placed)}
}

func (_c *MockKitchen_Receive_Call) Run(run func(ctx context.Context, placed kitchen.OrderCreated)) *MockKitchen_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kitchen.OrderCreated
		if args[1] != nil {
			arg1 = args[1].(kitchen.OrderCreated)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKitchen_Receive_Call) Return(err error) *MockKitchen_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKitchen_Receive_Call) RunAndReturn(run func(ctx context.Context, placed kitchen.OrderCreated) error) *MockKitchen_Receive_Call {
	_c.Call.Return(run)
	return _c
}
