// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/transport/sse"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

type MockHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHub) EXPECT() *MockHub_Expecter {
	return &MockHub_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockHub
func (_mock *MockHub) Publish(update sse.Update) {
	_mock.Called(update)
	return
}

// MockHub_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockHub_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - update sse.Update
func (_e *MockHub_Expecter) Publish(update any) *MockHub_Publish_Call {
	return &MockHub_Publish_Call{Call: _e.mock.On("Publish", update)}
}

func (_c *MockHub_Publish_Call) Run(run func(update sse.Update)) *MockHub_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sse.Update
		if args[0] != nil {
			arg0 = args[0].(sse.Update)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHub_Publish_Call) Return() *MockHub_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Publish_Call) RunAndReturn(run func(update sse.Update)) *MockHub_Publish_Call {
	_c.Run(run)
	return _c
}
