// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/cart"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// Cart provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) Cart(ctx context.Context, userID uuid.UUID) (cart.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Cart")
	}

	var r0 cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (cart.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) cart.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(cart.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartRepository_Cart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cart'
type MockCartRepository_Cart_Call struct {
	*mock.Call
}

// Cart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) Cart(ctx any, userID any) *MockCartRepository_Cart_Call {
	return &MockCartRepository_Cart_Call{Call: _e.mock.On("Cart", ctx, userID)}
}

func (_c *MockCartRepository_Cart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_Cart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_Cart_Call) Return(cart1 cart.Cart, err error) *MockCartRepository_Cart_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *MockCartRepository_Cart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (cart.Cart, error)) *MockCartRepository_Cart_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) Clear(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCartRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) Clear(ctx any, userID any) *MockCartRepository_Clear_Call {
	return &MockCartRepository_Clear_Call{Call: _e.mock.On("Clear", ctx, userID)}
}

func (_c *MockCartRepository_Clear_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_Clear_Call) Return(err error) *MockCartRepository_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_Clear_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockCartRepository_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) Lock(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockCartRepository_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) Lock(ctx any, userID any) *MockCartRepository_Lock_Call {
	return &MockCartRepository_Lock_Call{Call: _e.mock.On("Lock", ctx, userID)}
}

func (_c *MockCartRepository_Lock_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_Lock_Call) Return(err error) *MockCartRepository_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_Lock_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockCartRepository_Lock_Call {
	_c.Call.Return(run)
	return _c
}
