// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/order"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// ReleaseStock provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) ReleaseStock(ctx context.Context, venueID uuid.UUID, items []order.Item) error {
	ret := _mock.Called(ctx, venueID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []order.Item) error); ok {
		r0 = returnFunc(ctx, venueID, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMenuRepository_ReleaseStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStock'
type MockMenuRepository_ReleaseStock_Call struct {
	*mock.Call
}

// ReleaseStock is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - items []order.Item
func (_e *MockMenuRepository_Expecter) ReleaseStock(ctx any, venueID any, items any) *MockMenuRepository_ReleaseStock_Call {
	return &MockMenuRepository_ReleaseStock_Call{Call: _e.mock.On("ReleaseStock", ctx, venueID, items)}
}

func (_c *MockMenuRepository_ReleaseStock_Call) Run(run func(ctx context.Context, venueID uuid.UUID, items []order.Item)) *MockMenuRepository_ReleaseStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []order.Item
		if args[2] != nil {
			arg2 = args[2].([]order.Item)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMenuRepository_ReleaseStock_Call) Return(err error) *MockMenuRepository_ReleaseStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMenuRepository_ReleaseStock_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, items []order.Item) error) *MockMenuRepository_ReleaseStock_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveStock provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) ReserveStock(ctx context.Context, venueID uuid.UUID, items []order.Item) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, venueID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStock")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []order.Item) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, venueID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []order.Item) []uuid.UUID); ok {
		r0 = returnFunc(ctx, venueID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []order.Item) error); ok {
		r1 = returnFunc(ctx, venueID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_ReserveStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveStock'
type MockMenuRepository_ReserveStock_Call struct {
	*mock.Call
}

// ReserveStock is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - items []order.Item
func (_e *MockMenuRepository_Expecter) ReserveStock(ctx any, venueID any, items any) *MockMenuRepository_ReserveStock_Call {
	return &MockMenuRepository_ReserveStock_Call{Call: _e.mock.On("ReserveStock", ctx, venueID, items)}
}

func (_c *MockMenuRepository_ReserveStock_Call) Run(run func(ctx context.Context, venueID uuid.UUID, items []order.Item)) *MockMenuRepository_ReserveStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []order.Item
		if args[2] != nil {
			arg2 = args[2].([]order.Item)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMenuRepository_ReserveStock_Call) Return(uUIDs []uuid.UUID, err error) *MockMenuRepository_ReserveStock_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockMenuRepository_ReserveStock_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, items []order.Item) ([]uuid.UUID, error)) *MockMenuRepository_ReserveStock_Call {
	_c.Call.Return(run)
	return _c
}
