// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/outbox"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) Append(ctx context.Context, message outbox.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockOutboxRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - message outbox.Message
func (_e *MockOutboxRepository_Expecter) Append(ctx any, message any) *MockOutboxRepository_Append_Call {
	return &MockOutboxRepository_Append_Call{Call: _e.mock.On("Append", ctx, message)}
}

func (_c *MockOutboxRepository_Append_Call) Run(run func(ctx context.Context, message outbox.Message)) *MockOutboxRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.Message
		if args[1] != nil {
			arg1 = args[1].(outbox.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_Append_Call) Return(err error) *MockOutboxRepository_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxRepository_Append_Call) RunAndReturn(run func(ctx context.Context, message outbox.Message) error) *MockOutboxRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}
