// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/order"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApplyStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) ApplyStatus(ctx context.Context, orderID uuid.UUID, change order.StatusChange) (order.Applied, error) {
	ret := _mock.Called(ctx, orderID, change)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 order.Applied
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, order.StatusChange) (order.Applied, error)); ok {
		return returnFunc(ctx, orderID, change)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, order.StatusChange) order.Applied); ok {
		r0 = returnFunc(ctx, orderID, change)
	} else {
		r0 = ret.Get(0).(order.Applied)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, order.StatusChange) error); ok {
		r1 = returnFunc(ctx, orderID, change)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type MockRepository_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - change order.StatusChange
func (_e *MockRepository_Expecter) ApplyStatus(ctx any, orderID any, change any) *MockRepository_ApplyStatus_Call {
	return &MockRepository_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, orderID, change)}
}

func (_c *MockRepository_ApplyStatus_Call) Run(run func(ctx context.Context, orderID uuid.UUID, change order.StatusChange)) *MockRepository_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 order.StatusChange
		if args[2] != nil {
			arg2 = args[2].(order.StatusChange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ApplyStatus_Call) Return(applied order.Applied, err error) *MockRepository_ApplyStatus_Call {
	_c.Call.Return(applied, err)
	return _c
}

func (_c *MockRepository_ApplyStatus_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, change order.StatusChange) (order.Applied, error)) *MockRepository_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, draft order.Draft) (order.Order, error) {
	ret := _mock.Called(ctx, draft)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.Draft) (order.Order, error)); ok {
		return returnFunc(ctx, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.Draft) order.Order); ok {
		r0 = returnFunc(ctx, draft)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.Draft) error); ok {
		r1 = returnFunc(ctx, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - draft order.Draft
func (_e *MockRepository_Expecter) Create(ctx any, draft any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, draft)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, draft order.Draft)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.Draft
		if args[1] != nil {
			arg1 = args[1].(order.Draft)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(order1 order.Order, err error) *MockRepository_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, draft order.Draft) (order.Order, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, userID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, userID, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx any, userID any, orderID any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID, orderID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(order1 order.Order, err error) *MockRepository_Get_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (order.Order, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForVenue provides a mock function for the type MockRepository
func (_mock *MockRepository) GetForVenue(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, venueID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetForVenue")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, venueID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, venueID, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, venueID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetForVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForVenue'
type MockRepository_GetForVenue_Call struct {
	*mock.Call
}

// GetForVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetForVenue(ctx any, venueID any, orderID any) *MockRepository_GetForVenue_Call {
	return &MockRepository_GetForVenue_Call{Call: _e.mock.On("GetForVenue", ctx, venueID, orderID)}
}

func (_c *MockRepository_GetForVenue_Call) Run(run func(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID)) *MockRepository_GetForVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetForVenue_Call) Return(order1 order.Order, err error) *MockRepository_GetForVenue_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_GetForVenue_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID) (order.Order, error)) *MockRepository_GetForVenue_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, filter order.Filter) ([]order.Order, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.Filter) ([]order.Order, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.Filter) []order.Order); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter order.Filter
func (_e *MockRepository_Expecter) List(ctx any, filter any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter order.Filter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.Filter
		if args[1] != nil {
			arg1 = args[1].(order.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(orders []order.Order, err error) *MockRepository_List_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter order.Filter) ([]order.Order, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// LockForCustomer provides a mock function for the type MockRepository
func (_mock *MockRepository) LockForCustomer(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for LockForCustomer")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, userID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, userID, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockForCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockForCustomer'
type MockRepository_LockForCustomer_Call struct {
	*mock.Call
}

// LockForCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) LockForCustomer(ctx any, userID any, orderID any) *MockRepository_LockForCustomer_Call {
	return &MockRepository_LockForCustomer_Call{Call: _e.mock.On("LockForCustomer", ctx, userID, orderID)}
}

func (_c *MockRepository_LockForCustomer_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockRepository_LockForCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_LockForCustomer_Call) Return(order1 order.Order, err error) *MockRepository_LockForCustomer_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_LockForCustomer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (order.Order, error)) *MockRepository_LockForCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// LockForVenue provides a mock function for the type MockRepository
func (_mock *MockRepository) LockForVenue(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, venueID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for LockForVenue")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, venueID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, venueID, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, venueID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockForVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockForVenue'
type MockRepository_LockForVenue_Call struct {
	*mock.Call
}

// LockForVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) LockForVenue(ctx any, venueID any, orderID any) *MockRepository_LockForVenue_Call {
	return &MockRepository_LockForVenue_Call{Call: _e.mock.On("LockForVenue", ctx, venueID, orderID)}
}

func (_c *MockRepository_LockForVenue_Call) Run(run func(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID)) *MockRepository_LockForVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_LockForVenue_Call) Return(order1 order.Order, err error) *MockRepository_LockForVenue_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_LockForVenue_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, orderID uuid.UUID) (order.Order, error)) *MockRepository_LockForVenue_Call {
	_c.Call.Return(run)
	return _c
}

// LockUnaccepted provides a mock function for the type MockRepository
func (_mock *MockRepository) LockUnaccepted(ctx context.Context, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for LockUnaccepted")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockUnaccepted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockUnaccepted'
type MockRepository_LockUnaccepted_Call struct {
	*mock.Call
}

// LockUnaccepted is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) LockUnaccepted(ctx any, orderID any) *MockRepository_LockUnaccepted_Call {
	return &MockRepository_LockUnaccepted_Call{Call: _e.mock.On("LockUnaccepted", ctx, orderID)}
}

func (_c *MockRepository_LockUnaccepted_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_LockUnaccepted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_LockUnaccepted_Call) Return(order1 order.Order, err error) *MockRepository_LockUnaccepted_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockRepository_LockUnaccepted_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (order.Order, error)) *MockRepository_LockUnaccepted_Call {
	_c.Call.Return(run)
	return _c
}

// StaleUnaccepted provides a mock function for the type MockRepository
func (_mock *MockRepository) StaleUnaccepted(ctx context.Context, before time.Time, limit int) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for StaleUnaccepted")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []uuid.UUID); ok {
		r0 = returnFunc(ctx, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_StaleUnaccepted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaleUnaccepted'
type MockRepository_StaleUnaccepted_Call struct {
	*mock.Call
}

// StaleUnaccepted is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - limit int
func (_e *MockRepository_Expecter) StaleUnaccepted(ctx any, before any, limit any) *MockRepository_StaleUnaccepted_Call {
	return &MockRepository_StaleUnaccepted_Call{Call: _e.mock.On("StaleUnaccepted", ctx, before, limit)}
}

func (_c *MockRepository_StaleUnaccepted_Call) Run(run func(ctx context.Context, before time.Time, limit int)) *MockRepository_StaleUnaccepted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_StaleUnaccepted_Call) Return(uUIDs []uuid.UUID, err error) *MockRepository_StaleUnaccepted_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockRepository_StaleUnaccepted_Call) RunAndReturn(run func(ctx context.Context, before time.Time, limit int) ([]uuid.UUID, error)) *MockRepository_StaleUnaccepted_Call {
	_c.Call.Return(run)
	return _c
}
