// Package kitchenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package kitchenapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CartProblemType.
const (
	CartProblemTypeBelowMinimum    CartProblemType = "below_minimum"
	CartProblemTypeItemUnavailable CartProblemType = "item_unavailable"
	CartProblemTypeOutOfStock      CartProblemType = "out_of_stock"
	CartProblemTypePriceChanged    CartProblemType = "price_changed"
	CartProblemTypeVenueClosed     CartProblemType = "venue_closed"
)

// Valid indicates whether the value is a known member of the CartProblemType enum.
func (e CartProblemType) Valid() bool {
	switch e {
	case CartProblemTypeBelowMinimum:
		return true
	case CartProblemTypeItemUnavailable:
		return true
	case CartProblemTypeOutOfStock:
		return true
	case CartProblemTypePriceChanged:
		return true
	case CartProblemTypeVenueClosed:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	ACCEPTED   OrderStatus = "ACCEPTED"
	CANCELLED  OrderStatus = "CANCELLED"
	COOKING    OrderStatus = "COOKING"
	CREATED    OrderStatus = "CREATED"
	DELIVERED  OrderStatus = "DELIVERED"
	DELIVERING OrderStatus = "DELIVERING"
	READY      OrderStatus = "READY"
	REJECTED   OrderStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case CANCELLED:
		return true
	case COOKING:
		return true
	case CREATED:
		return true
	case DELIVERED:
		return true
	case DELIVERING:
		return true
	case READY:
		return true
	case REJECTED:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableReason.
const (
	UnavailableReasonOutOfStock  UnavailableReason = "out_of_stock"
	UnavailableReasonStopped     UnavailableReason = "stopped"
	UnavailableReasonVenueClosed UnavailableReason = "venue_closed"
)

// Valid indicates whether the value is a known member of the UnavailableReason enum.
func (e UnavailableReason) Valid() bool {
	switch e {
	case UnavailableReasonOutOfStock:
		return true
	case UnavailableReasonStopped:
		return true
	case UnavailableReasonVenueClosed:
		return true
	default:
		return false
	}
}

// Defines values for VenueSort.
const (
	AvgCookMinutes VenueSort = "avg_cook_minutes"
	DeliveryFee    VenueSort = "delivery_fee"
	Name           VenueSort = "name"
)

// Valid indicates whether the value is a known member of the VenueSort enum.
func (e VenueSort) Valid() bool {
	switch e {
	case AvgCookMinutes:
		return true
	case DeliveryFee:
		return true
	case Name:
		return true
	default:
		return false
	}
}

// CancelOrderRequest defines model for CancelOrderRequest.
type CancelOrderRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// Cart defines model for Cart.
type Cart struct {
	// DeliveryFee Сумма в копейках.
	DeliveryFee Money      `json:"delivery_fee"`
	Items       []CartItem `json:"items"`

	// ItemsTotal Сумма в копейках.
	ItemsTotal     Money  `json:"items_total"`
	MinOrderAmount *Money `json:"min_order_amount,omitempty"`

	// Total Сумма в копейках.
	Total Money `json:"total"`

	// VenueId Заведение корзины; `null` — корзина пуста.
	VenueId   *openapi_types.UUID `json:"venue_id,omitempty"`
	VenueName *string             `json:"venue_name,omitempty"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	ExternalId  string             `json:"external_id"`
	IsAvailable bool               `json:"is_available"`
	ItemId      openapi_types.UUID `json:"item_id"`

	// LineTotal Сумма в копейках.
	LineTotal Money  `json:"line_total"`
	Name      string `json:"name"`

	// Price Сумма в копейках.
	Price Money `json:"price"`
	Qty   int   `json:"qty"`
}

// CartProblem defines model for CartProblem.
type CartProblem struct {
	AvailableQty *int                `json:"available_qty,omitempty"`
	ItemId       *openapi_types.UUID `json:"item_id,omitempty"`
	ItemName     *string             `json:"item_name,omitempty"`
	Message      string              `json:"message"`
	NewPrice     *Money              `json:"new_price,omitempty"`

	// OldPrice Цена, по которой позиция лежала в корзине.
	OldPrice     *Money `json:"old_price,omitempty"`
	RequestedQty *int   `json:"requested_qty,omitempty"`

	// Shortfall Сколько добрать до минимальной суммы заказа.
	Shortfall *Money          `json:"shortfall,omitempty"`
	Type      CartProblemType `json:"type"`
}

// CartProblemType defines model for CartProblemType.
type CartProblemType string

// CartValidation defines model for CartValidation.
type CartValidation struct {
	// Cart Корзина, пересчитанная по актуальному меню.
	Cart Cart `json:"cart"`

	// IsValid Проблем нет, заказ можно оформлять.
	IsValid  bool          `json:"is_valid"`
	Problems []CartProblem `json:"problems"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Address string  `json:"address"`
	Comment *string `json:"comment,omitempty"`

	// ExpectedTotal Итоговая сумма, показанная пользователю.
	ExpectedTotal Money  `json:"expected_total"`
	Phone         string `json:"phone"`
}

// Cuisine defines model for Cuisine.
type Cuisine struct {
	// Name Example: Пекарня
	Name string `json:"name"`

	// Slug Example: bakery
	Slug string `json:"slug"`
}

// CuisineList defines model for CuisineList.
type CuisineList struct {
	Items []Cuisine `json:"items"`
}

// Error defines model for Error.
type Error struct {
	// Code Машиночитаемый код ошибки.
	//
	// Example: price_mismatch
	Code string `json:"code"`

	// Details Подробности, зависящие от кода.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Человекочитаемое описание.
	Message string `json:"message"`

	// TraceId Идентификатор запроса; он же в логах сервиса.
	TraceId *string `json:"trace_id,omitempty"`
}

// Menu defines model for Menu.
type Menu struct {
	Categories []MenuCategory     `json:"categories"`
	VenueId    openapi_types.UUID `json:"venue_id"`
}

// MenuCategory defines model for MenuCategory.
type MenuCategory struct {
	ExternalId string             `json:"external_id"`
	Id         openapi_types.UUID `json:"id"`
	Items      []MenuItem         `json:"items"`
	Name       string             `json:"name"`
	Position   int                `json:"position"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	Description *string `json:"description,omitempty"`

	// ExternalId Идентификатор позиции в системе заведения.
	ExternalId  string             `json:"external_id"`
	Id          openapi_types.UUID `json:"id"`
	IsAvailable bool               `json:"is_available"`
	Name        string             `json:"name"`

	// Position Порядок позиции внутри категории, заданный заведением.
	Position int `json:"position"`

	// Price Сумма в копейках.
	Price Money `json:"price"`

	// StockQty Остаток; `null` — не ограничен.
	StockQty *int `json:"stock_qty,omitempty"`

	// UnavailableReason Заполнено, когда `is_available` равно `false`.
	UnavailableReason *UnavailableReason `json:"unavailable_reason,omitempty"`
}

// Money Сумма в копейках.
type Money = int64

// Order defines model for Order.
type Order struct {
	Address   *string   `json:"address,omitempty"`
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// DeliveryFee Сумма в копейках.
	DeliveryFee Money `json:"delivery_fee"`

	// EtaMinutes Оценка времени готовности, названная заведением.
	EtaMinutes *int               `json:"eta_minutes,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Items      []OrderItem        `json:"items"`

	// ItemsTotal Сумма в копейках.
	ItemsTotal Money `json:"items_total"`

	// Number Человекочитаемый номер заказа.
	//
	// Example: AK-100042
	Number          string      `json:"number"`
	Phone           string      `json:"phone"`
	RejectionReason *string     `json:"rejection_reason,omitempty"`
	Status          OrderStatus `json:"status"`

	// Total Сумма в копейках.
	Total     Money      `json:"total"`
	UpdatedAt time.Time  `json:"updated_at"`
	Venue     OrderVenue `json:"venue"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	ExternalId string `json:"external_id"`

	// LineTotal Сумма в копейках.
	LineTotal Money `json:"line_total"`

	// Name Название на момент оформления заказа.
	Name string `json:"name"`

	// Price Сумма в копейках.
	Price Money `json:"price"`
	Qty   int   `json:"qty"`
}

// OrderList defines model for OrderList.
type OrderList struct {
	Items      []Order `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderVenue defines model for OrderVenue.
type OrderVenue struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// PutCartItemRequest defines model for PutCartItemRequest.
type PutCartItemRequest struct {
	ItemId openapi_types.UUID `json:"item_id"`

	// Qty Итоговое количество; `0` удаляет позицию.
	Qty     int                `json:"qty"`
	VenueId openapi_types.UUID `json:"venue_id"`
}

// UnavailableReason defines model for UnavailableReason.
type UnavailableReason string

// Venue defines model for Venue.
type Venue struct {
	Address        string    `json:"address"`
	AvgCookMinutes int       `json:"avg_cook_minutes"`
	Cuisines       []Cuisine `json:"cuisines"`

	// DeliveryFee Сумма в копейках.
	DeliveryFee Money              `json:"delivery_fee"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// IsOpen Смена заведения открыта, заказы принимаются.
	IsOpen bool     `json:"is_open"`
	Lat    *float64 `json:"lat,omitempty"`
	Lon    *float64 `json:"lon,omitempty"`

	// MinOrderAmount Сумма в копейках.
	MinOrderAmount Money  `json:"min_order_amount"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
}

// VenueList defines model for VenueList.
type VenueList struct {
	Items []Venue `json:"items"`

	// NextCursor Курсор следующей страницы; `null` — страница последняя.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// VenueSort defines model for VenueSort.
type VenueSort string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// VenueId defines model for VenueId.
type VenueId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalError defines model for InternalError.
type InternalError = Error

// InvalidTransition defines model for InvalidTransition.
type InvalidTransition = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Status Фильтр по статусу; можно передать несколько значений.
	Status *[]OrderStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Курсор следующей страницы из поля `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Размер страницы.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// IdempotencyKey Уникальный ключ попытки оформления.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ListVenuesParams defines parameters for ListVenues.
type ListVenuesParams struct {
	// Q Поиск по названию заведения.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Cuisine Слаг кухни из справочника `/cuisines`.
	Cuisine *string `form:"cuisine,omitempty" json:"cuisine,omitempty"`

	// OpenNow Только заведения с открытой сменой.
	OpenNow *bool      `form:"open_now,omitempty" json:"open_now,omitempty"`
	Sort    *VenueSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Cursor Курсор следующей страницы из поля `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Размер страницы.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutCartItemJSONRequestBody defines body for PutCartItem for application/json ContentType.
type PutCartItemJSONRequestBody = PutCartItemRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// CancelOrderJSONRequestBody defines body for CancelOrder for application/json ContentType.
type CancelOrderJSONRequestBody = CancelOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ClearCart Очистить корзину
	// (DELETE /cart)
	ClearCart(w http.ResponseWriter, r *http.Request)
	// GetCart Текущая корзина
	// (GET /cart)
	GetCart(w http.ResponseWriter, r *http.Request)
	// PutCartItem Задать количество позиции в корзине
	// (PUT /cart/items)
	PutCartItem(w http.ResponseWriter, r *http.Request)
	// DeleteCartItem Удалить позицию из корзины
	// (DELETE /cart/items/{item_id})
	DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// ValidateCart Проверить корзину перед оформлением
	// (POST /cart/validate)
	ValidateCart(w http.ResponseWriter, r *http.Request)
	// ListCuisines Справочник кухонь
	// (GET /cuisines)
	ListCuisines(w http.ResponseWriter, r *http.Request)
	// ListOrders Заказы пользователя
	// (GET /orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// CreateOrder Оформить заказ
	// (POST /orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetOrder Карточка заказа
	// (GET /orders/{order_id})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// CancelOrder Отменить заказ
	// (POST /orders/{order_id}/cancel)
	CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// ListVenues Список заведений
	// (GET /venues)
	ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams)
	// GetVenue Карточка заведения
	// (GET /venues/{venue_id})
	GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId)
	// GetVenueMenu Меню заведения
	// (GET /venues/{venue_id}/menu)
	GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ClearCart Очистить корзину
// (DELETE /cart)
func (_ Unimplemented) ClearCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCart Текущая корзина
// (GET /cart)
func (_ Unimplemented) GetCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PutCartItem Задать количество позиции в корзине
// (PUT /cart/items)
func (_ Unimplemented) PutCartItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteCartItem Удалить позицию из корзины
// (DELETE /cart/items/{item_id})
func (_ Unimplemented) DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ValidateCart Проверить корзину перед оформлением
// (POST /cart/validate)
func (_ Unimplemented) ValidateCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCuisines Справочник кухонь
// (GET /cuisines)
func (_ Unimplemented) ListCuisines(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListOrders Заказы пользователя
// (GET /orders)
func (_ Unimplemented) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrder Оформить заказ
// (POST /orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetOrder Карточка заказа
// (GET /orders/{order_id})
func (_ Unimplemented) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelOrder Отменить заказ
// (POST /orders/{order_id}/cancel)
func (_ Unimplemented) CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVenues Список заведений
// (GET /venues)
func (_ Unimplemented) ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVenue Карточка заведения
// (GET /venues/{venue_id})
func (_ Unimplemented) GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVenueMenu Меню заведения
// (GET /venues/{venue_id}/menu)
func (_ Unimplemented) GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ClearCart operation middleware
func (siw *ServerInterfaceWrapper) ClearCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCart operation middleware
func (siw *ServerInterfaceWrapper) GetCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutCartItem operation middleware
func (siw *ServerInterfaceWrapper) PutCartItem(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutCartItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCartItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCartItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateCart operation middleware
func (siw *ServerInterfaceWrapper) ValidateCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCuisines operation middleware
func (siw *ServerInterfaceWrapper) ListCuisines(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCuisines(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelOrder operation middleware
func (siw *ServerInterfaceWrapper) CancelOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVenues operation middleware
func (siw *ServerInterfaceWrapper) ListVenues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVenuesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cuisine" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cuisine", r.URL.Query(), &params.Cuisine, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cuisine"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cuisine", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "open_now" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "open_now", r.URL.Query(), &params.OpenNow, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "open_now"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "open_now", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVenues(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenue operation middleware
func (siw *ServerInterfaceWrapper) GetVenue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venue_id" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venue_id", chi.URLParam(r, "venue_id"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venue_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenue(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenueMenu operation middleware
func (siw *ServerInterfaceWrapper) GetVenueMenu(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venue_id" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venue_id", chi.URLParam(r, "venue_id"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venue_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenueMenu(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cuisines", wrapper.ListCuisines)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues", wrapper.ListVenues)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues/{venue_id}", wrapper.GetVenue)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/venues/{venue_id}/menu", wrapper.GetVenueMenu)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cart", wrapper.ClearCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cart", wrapper.GetCart)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/cart/items", wrapper.PutCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cart/items/{item_id}", wrapper.DeleteCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cart/validate", wrapper.ValidateCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders", wrapper.ListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{order_id}", wrapper.GetOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders/{order_id}/cancel", wrapper.CancelOrder)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type InternalErrorJSONResponse Error

type InvalidTransitionJSONResponse Error

type NotFoundJSONResponse Error

type ClearCartRequestObject struct {
}

type ClearCartResponseObject interface {
	VisitClearCartResponse(w http.ResponseWriter) error
}

type ClearCart204Response struct {
}

func (response ClearCart204Response) VisitClearCartResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ClearCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response ClearCart500JSONResponse) VisitClearCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCartRequestObject struct {
}

type GetCartResponseObject interface {
	VisitGetCartResponse(w http.ResponseWriter) error
}

type GetCart200JSONResponse Cart

func (response GetCart200JSONResponse) VisitGetCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetCart500JSONResponse) VisitGetCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItemRequestObject struct {
	Body *PutCartItemJSONRequestBody
}

type PutCartItemResponseObject interface {
	VisitPutCartItemResponse(w http.ResponseWriter) error
}

type PutCartItem200JSONResponse Cart

func (response PutCartItem200JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem400JSONResponse struct{ BadRequestJSONResponse }

func (response PutCartItem400JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem404JSONResponse struct{ NotFoundJSONResponse }

func (response PutCartItem404JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem409JSONResponse struct{ ConflictJSONResponse }

func (response PutCartItem409JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutCartItem500JSONResponse struct{ InternalErrorJSONResponse }

func (response PutCartItem500JSONResponse) VisitPutCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItemRequestObject struct {
	ItemId openapi_types.UUID `json:"item_id"`
}

type DeleteCartItemResponseObject interface {
	VisitDeleteCartItemResponse(w http.ResponseWriter) error
}

type DeleteCartItem200JSONResponse Cart

func (response DeleteCartItem200JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItem404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCartItem404JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCartItem500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteCartItem500JSONResponse) VisitDeleteCartItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateCartRequestObject struct {
}

type ValidateCartResponseObject interface {
	VisitValidateCartResponse(w http.ResponseWriter) error
}

type ValidateCart200JSONResponse CartValidation

func (response ValidateCart200JSONResponse) VisitValidateCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ValidateCart500JSONResponse struct{ InternalErrorJSONResponse }

func (response ValidateCart500JSONResponse) VisitValidateCartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListCuisinesRequestObject struct {
}

type ListCuisinesResponseObject interface {
	VisitListCuisinesResponse(w http.ResponseWriter) error
}

type ListCuisines200JSONResponse CuisineList

func (response ListCuisines200JSONResponse) VisitListCuisinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCuisines500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListCuisines500JSONResponse) VisitListCuisinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrdersRequestObject struct {
	Params ListOrdersParams
}

type ListOrdersResponseObject interface {
	VisitListOrdersResponse(w http.ResponseWriter) error
}

type ListOrders200JSONResponse OrderList

func (response ListOrders200JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response ListOrders400JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrders500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListOrders500JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Params CreateOrderParams
	Body   *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder200JSONResponse Order

func (response CreateOrder200JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409JSONResponse Error

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder422JSONResponse Error

func (response CreateOrder422JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse Order

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetOrder500JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
	Body    *CancelOrderJSONRequestBody
}

type CancelOrderResponseObject interface {
	VisitCancelOrderResponse(w http.ResponseWriter) error
}

type CancelOrder200JSONResponse Order

func (response CancelOrder200JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelOrder404JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder409JSONResponse struct{ InvalidTransitionJSONResponse }

func (response CancelOrder409JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response CancelOrder500JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenuesRequestObject struct {
	Params ListVenuesParams
}

type ListVenuesResponseObject interface {
	VisitListVenuesResponse(w http.ResponseWriter) error
}

type ListVenues200JSONResponse VenueList

func (response ListVenues200JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenues400JSONResponse struct{ BadRequestJSONResponse }

func (response ListVenues400JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListVenues500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVenues500JSONResponse) VisitListVenuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueRequestObject struct {
	VenueId VenueId `json:"venue_id"`
}

type GetVenueResponseObject interface {
	VisitGetVenueResponse(w http.ResponseWriter) error
}

type GetVenue200JSONResponse Venue

func (response GetVenue200JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenue404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVenue404JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenue500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVenue500JSONResponse) VisitGetVenueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenuRequestObject struct {
	VenueId VenueId `json:"venue_id"`
}

type GetVenueMenuResponseObject interface {
	VisitGetVenueMenuResponse(w http.ResponseWriter) error
}

type GetVenueMenu200JSONResponse Menu

func (response GetVenueMenu200JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenu404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVenueMenu404JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVenueMenu500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVenueMenu500JSONResponse) VisitGetVenueMenuResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ClearCart Очистить корзину
	// (DELETE /cart)
	ClearCart(ctx context.Context, request ClearCartRequestObject) (ClearCartResponseObject, error)
	// GetCart Текущая корзина
	// (GET /cart)
	GetCart(ctx context.Context, request GetCartRequestObject) (GetCartResponseObject, error)
	// PutCartItem Задать количество позиции в корзине
	// (PUT /cart/items)
	PutCartItem(ctx context.Context, request PutCartItemRequestObject) (PutCartItemResponseObject, error)
	// DeleteCartItem Удалить позицию из корзины
	// (DELETE /cart/items/{item_id})
	DeleteCartItem(ctx context.Context, request DeleteCartItemRequestObject) (DeleteCartItemResponseObject, error)
	// ValidateCart Проверить корзину перед оформлением
	// (POST /cart/validate)
	ValidateCart(ctx context.Context, request ValidateCartRequestObject) (ValidateCartResponseObject, error)
	// ListCuisines Справочник кухонь
	// (GET /cuisines)
	ListCuisines(ctx context.Context, request ListCuisinesRequestObject) (ListCuisinesResponseObject, error)
	// ListOrders Заказы пользователя
	// (GET /orders)
	ListOrders(ctx context.Context, request ListOrdersRequestObject) (ListOrdersResponseObject, error)
	// CreateOrder Оформить заказ
	// (POST /orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// GetOrder Карточка заказа
	// (GET /orders/{order_id})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// CancelOrder Отменить заказ
	// (POST /orders/{order_id}/cancel)
	CancelOrder(ctx context.Context, request CancelOrderRequestObject) (CancelOrderResponseObject, error)
	// ListVenues Список заведений
	// (GET /venues)
	ListVenues(ctx context.Context, request ListVenuesRequestObject) (ListVenuesResponseObject, error)
	// GetVenue Карточка заведения
	// (GET /venues/{venue_id})
	GetVenue(ctx context.Context, request GetVenueRequestObject) (GetVenueResponseObject, error)
	// GetVenueMenu Меню заведения
	// (GET /venues/{venue_id}/menu)
	GetVenueMenu(ctx context.Context, request GetVenueMenuRequestObject) (GetVenueMenuResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ClearCart operation middleware
func (sh *strictHandler) ClearCart(w http.ResponseWriter, r *http.Request) {
	var request ClearCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClearCart(ctx, request.(ClearCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClearCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClearCartResponseObject); ok {
		if err := validResponse.VisitClearCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCart operation middleware
func (sh *strictHandler) GetCart(w http.ResponseWriter, r *http.Request) {
	var request GetCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCart(ctx, request.(GetCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCartResponseObject); ok {
		if err := validResponse.VisitGetCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutCartItem operation middleware
func (sh *strictHandler) PutCartItem(w http.ResponseWriter, r *http.Request) {
	var request PutCartItemRequestObject

	var body PutCartItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutCartItem(ctx, request.(PutCartItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutCartItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutCartItemResponseObject); ok {
		if err := validResponse.VisitPutCartItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCartItem operation middleware
func (sh *strictHandler) DeleteCartItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	var request DeleteCartItemRequestObject

	request.ItemId = itemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCartItem(ctx, request.(DeleteCartItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCartItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCartItemResponseObject); ok {
		if err := validResponse.VisitDeleteCartItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidateCart operation middleware
func (sh *strictHandler) ValidateCart(w http.ResponseWriter, r *http.Request) {
	var request ValidateCartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidateCart(ctx, request.(ValidateCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidateCart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidateCartResponseObject); ok {
		if err := validResponse.VisitValidateCartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCuisines operation middleware
func (sh *strictHandler) ListCuisines(w http.ResponseWriter, r *http.Request) {
	var request ListCuisinesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCuisines(ctx, request.(ListCuisinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCuisines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCuisinesResponseObject); ok {
		if err := validResponse.VisitListCuisinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrders operation middleware
func (sh *strictHandler) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	var request ListOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrders(ctx, request.(ListOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrdersResponseObject); ok {
		if err := validResponse.VisitListOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	var request CreateOrderRequestObject

	request.Params = params

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelOrder operation middleware
func (sh *strictHandler) CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request CancelOrderRequestObject

	request.OrderId = orderId

	var body CancelOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelOrder(ctx, request.(CancelOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelOrderResponseObject); ok {
		if err := validResponse.VisitCancelOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVenues operation middleware
func (sh *strictHandler) ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams) {
	var request ListVenuesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVenues(ctx, request.(ListVenuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVenues")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVenuesResponseObject); ok {
		if err := validResponse.VisitListVenuesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVenue operation middleware
func (sh *strictHandler) GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	var request GetVenueRequestObject

	request.VenueId = venueId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVenue(ctx, request.(GetVenueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVenue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVenueResponseObject); ok {
		if err := validResponse.VisitGetVenueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVenueMenu operation middleware
func (sh *strictHandler) GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId) {
	var request GetVenueMenuRequestObject

	request.VenueId = venueId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVenueMenu(ctx, request.(GetVenueMenuRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVenueMenu")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVenueMenuResponseObject); ok {
		if err := validResponse.VisitGetVenueMenuResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fxvb9tGmv8qBO9eMrLiZg+o8irr+Apf0yZI0uAOcSAy0tjhViIVknJjGAZsaxMnSC7eLBbootjdNu3h",
	"+lZVrFi2JeUrzHyF+ySH55kZcigO9ceW0+6rRBZn+Mw8/37Pb57Rllnx6w3fI14UmqUts+EETp1EJMBP",
	"S80g9AP4X5WElcBtRK7vmSWTfsdabIft0iHbMdguPaVdesha7DV7Qbv02GC7bI/t0DYd0B57xl4atEeP",
	"DPqBDukpOzBsjzyJyhWc3C6YlunCpI+bJNg0LdNz6sQsmfxr0zLDyiNSd0CIaLMB34RR4Hrr5va2Zd5w",
	"626kke8H2qZHtE+7KF9amLwX1nAu9X1VsuY0a5FZWixaZt154tabdbN0uQifXE98sqRYrheRdRKgXDeD",
	"KglWqjAJvqrhRI+SN/nwbdmtmpYZkMdNNyBVsxQFTaK+fM0P6k5klsxmE5/MLv4e8Zok9yUb8O15X7IN",
	"g8OG74UEDeL3TvU2edwkIW56xfci4uF/nUaj5lYc2P+FP4SghC3lNf8akDWzZP7LQmJsC/zbcGE5CPyA",
	"v2pEid/SNv3AduiQ7Rp0QLuG+PScvaGnBu3QNj2lPXpI2+wZ7bHX5rZlLvneWs2tfAzx/gKmDsZFO7SX",
	"SLdHe7QDjkG7bJ/22J7B9miXnrAWOkeftQx0HBg4ZAdolSj6iheRwHNq/I0XL/+f6YC10DW6dEAH7IAd",
	"GLC7tEd/oSe0zWXacGpu9W7geKHLB164XN+D19Iue0qH9NCgR8IKuuwFe0MHPJSktvQdHaKT0zbbYy22",
	"S9t81AkGAVzHl370737Tq34E8X+gXbbLw6Ow2gFt02N6CNtcMOjPrEXf0yE9VoSE9cB/38PjYEJg02/Y",
	"HtsFncAjJ4Yt12AXVj30fyELBmrHq5AaRh3FPxuB3yBB5HLfDYgjllh3ntwg3nr0yCz9DoJZNrSIv/gP",
	"/0AqEfqVE2imrJKau0GCzfIaIZN27AvfI5swlRuROo6O/zNuGLx4JSJ1M5HKCQInmakc+ZFTm/rtddcr",
	"8/jr1P2mMINa7eaaWbo/1RQPLNNr1mrOwxrh8RQEm0mEODJn8xaEvA4kU/RJjConGEuOaI8O2Murhg0v",
	"t43/2/lL6iuw+Q9g/GBJkOFGI3ta5ozOpVQ8eWxNenxbTSr3hSbTCrHS1iE36UGOcaGOMwZGnvCYKHYr",
	"I7Qblp0NxxWixg889P0acTxpI2L0hGRnmTXXIzOak9yvzFyNwK1M7xOPo010zPGoYnTLeXZX90gIJF/P",
	"J04tbGTP8tRxK/Af1nQaiYeWhcw5lhLLPVYFE60Sx05plJZZJ2HorOsV4pFvyrFSzu3xfq169tlGnP5/",
	"0dnbFgJk7tV76NmYJAA0HwFypT1IBgC13yPyaRu0k44B3YKpETXgCYFUp9dY+MgPojWnVpvD6t6CiPSU",
	"vYJ/DXpIh/QXgONsj73Cjwbto/Q92od1sVd0gCuHLEr7tA/lg5LOtWvkS5icSYRZ34XHRz0K50hsaIJn",
	"3BVvJB74633ucOXKI8dbJ2DZfjMq+2vlMPIrX4vIWG56iePJgFup+SEOeEhq/jdlGQEeaKwb3n4P4Jgj",
	"kVjaNSsiR0+nMMzoGn19pyYVtEkOx3Y5msU6akDbYItorm16ArBLUR1AXKi96IC9LogojTBSk/C+RzP/",
	"Bc26j3iJ7VkqMqJ9OqTvYV5ARn9E4fpQRYL9FJIoroT8BtfQbBhDBrwMzBiNu3ItynssvvVaiwmIE5Hx",
	"wMypVgMShjpkVnc9+fmyxiIqfr0uoOwETAdpokEqEAXiBHdOx/4rRCkA31CJsYPYX2Ukkw6bshc0kiMx",
	"BkD8qbCRxiPfIyML+WRxwg6M6EZupJwts2ithppu6PJXp9Uisw554tQbEGuwNIFVsR0ol3QIIqw119Nj",
	"Hjpfc5ZhvOg4UGTvMVLecHUGNCOiFgueaOk4mU6YuEIdiT9+lWhc/G+0jUXlgA7jEAJ18EvIbie8yEvK",
	"zl4B1Sa3j4fVuhvWnajySLflVRI5bk06EhapTu2WIhhPcpkic0gPRewZiGq8JwJPh/ag8GIvOAAfsj0h",
	"J08+me1QUMfIW34GA0dj72KiVpZPhzg3/QAv4+QUz9+ZBUaBU8kpF/7KCwWQnf2R9tA2ETokZfMQZr8K",
	"bxoYvL7sGCjTO9pmTw22i+G9w6UoTLRT1PH4JPkF8Zq65BSRdT8YtdixkYd4zSU+bFNX/ql11GS2TF2F",
	"wo0pcuUtJpZh9vJkurpjNv8FkfIq4vxyxE/4m0mVRX5RISexxgSHWDwNW6AY75YuQ6V2c3pbVyAy7YGB",
	"s1104T10tK706risZgdaR5tWWxNrzqm0kA1IbIcdID4+yS4p5up6hlg58l7whzhuHfJcywPr0SiTQPvK",
	"ohWsP1uhinhWFhIjS/iHJOFgCWmmYsCD3buYh99HNiy/AlQEVFBzOeGwpgMvXyVjb/OhGiCDPDNAExAT",
	"soHF4/072FHDVvVtG7iCDuJRe82phcTWFCTTe5Qo01XPmlSec11kt/+thF+yLgToTo/RXJ6mKCHXi/7t",
	"iqkcYhR1+46gdSxanViPK/g0+x0i42rZiVJeV3UicilycXc0uf4MfCOJHCirmpEmCoHRPkOln+C+IRne",
	"5y5joIPtYfpWIcIAYW1HBbY5zjYFNXIRCYIfPs2RM/Wa9YckmA3f8CiE5SCewo2W8AnEu/b5pcvFYvHK",
	"om7lcVmQ+SYg4BCu7ylBYaJBhpETNafbwDv80ZnZ3WajOrNdIx6ZSio889OnbKElOVu8WGsWejYpnRT/",
	"TC1KF5ISi5sZIp2Dcx0xxr8rftkT5y6cPuBcxF6KQJBIIGOY82FyJ2Cs2Tjb3C2fRznIw7wOSyaH9Gc9",
	"EcgV/E7sh5I/W7q9fO3u8nXTMq8tLS3f4v9dunnz85UvPzMt8/bytev/ZVrm9eUbK/eWb/M/ig/46O3l",
	"/1heEqOufbm0fOPG8nUti6a4UXbnpgvHOfhO65R5Bf2tZiSPPXKJoVnOLvSQTOVohuI0iZ5y/CWOrodX",
	"DbtoG6yF+PGUHdAuuIpKO78Gv8jpf9BCh7lUZskJB6xNt4dZdKcYVBj5jYaOik3xrjoLyTEOBfhkhjgb",
	"6+WK73+tAo3stlQ48zIHquaMUGhSBTZ9BeQ3iK6KeSvAU1tTc/GT7RO2w14CSFBZXvaSd0/ExwDsNT/8",
	"1hO8tdHc6jc5pZ4To0RmhJF84WcYqTs3Pt8JoeQKp4giKjtoKTRnbFCJTjSSZlJ9xlp1zoVeMI8EIyDL",
	"xARzvhazVL2Z/hLPxpEIw0l4q0th8unj1CkNV3jHD6JU05hUlwxI4uP0ulDkCEmlGbjR5h3YU66Er0LZ",
	"YTYbUZIl4A8s46uvVq7HfXGPiFNFICk6yf7zErzr0ooSC5yG+zmYN8jmemt+Voxrt1YM9P9fLtET7NPi",
	"MqEuTumQvUDG4oT2SpLRaHNeMltOHVsjvQ6jsaPHFYzEw6qX6gUaQjGsQrxVb9VD+je7Ea8MbCdTNg/T",
	"3w5rQU7kzTgw1TtMojAS0mnfsOMdsgsG/RNr4XxpDTyLweaqh6bZR4n6tGd8ce9WyVDO17q0bxlsH5aT",
	"ESilTYiYshsOWeoOe8mei8w+RAZbdEc9p6fsdbL8P7NdAAN8f7v0PZJGXa4vjg6w24T70jNR5HUNlBC8",
	"aJjwC116UliFsBO5ET8k+ROyyXt0WEAffgr+JvtVYjtgu6B6emxcu7WCOTkIud1cLhQLRXAqiGZOwzVL",
	"5ieFYuETwMdO9AhNf0GedFZJjUQYXSE84bEouIS5VCNOgAecI/2Li8UrulCT7qPhdewLnshAlN8Vi3lB",
	"Lp59Id2+h07brNedYJOzDPuCkezxc2+1q6cFu+esh8iv40HitmWukyi7rs9IpF9VcW6NbfxYWNPXNrJJ",
	"OaHkqsFavOzvcOCZ+yQ3ibhniR3MZ6d/jBsD27x3TpE6u8/bFjemhTiTNZq6fuKfuJDI/XTQiqHORKDc",
	"mwJiFwz7cbRZMibibO6dI10dvIh9B2El7v/gVpRmiVGQuNFiCJlO6iADxkqZxpJDjHPv+IhVT4ffPnD+",
	"GUKG1NtQHOIp0oJe7SvFTw3Y2LJA26It1+axIm3VSilkxu0qv/erm3Mzak2xtZ1O73GvzMd2q+/z2yvS",
	"trttmVem8Q6lRRuHXJk8JO6OxQGfTh4Qd1nPxWW/5WcXcWAc9R7NAU/a5Cb59cKWqCW3xyWN6/h3xRLV",
	"uxD3z3EeFbfCWLo+/aTMPXub/oPfvuXOaIbnt6qfeJyVCTcVZ8V9lFRr7Rgj2uBNV5wT8MNIW/h2YDtk",
	"VE+ld4Ptqg3rPdrP3ADg3U/CUBDPasIvngPCKjrYP/eCZyDAu6KLgJ8cqh1VBYN+l4AuA3vvDnhTDqJF",
	"TpjyHeqyN3G3Fz002H9DrY5aBYyr405Lq5596+adu8YC1puhnZMicL1cxJP4okTS9CWWynbYc9TWbvoi",
	"wpAe67KG6IQjHwMQKV13OS3/9Ii1IPfyykMuEVcFQPfqyKKR8BD+I0F1FyE37Ri2bCyz5+MJ3yuy6OCn",
	"qvWsmkHcHN9Q6CwBVzMnqxAQ9hMTPkTkh/ESNwsMzLDFRLY4ulcsJVMJFjJ2cMMNo6WEB7k4O1A6sHRG",
	"8BY13Ma7P/so7ImBHv+UDumAvZqPLie+RdVU5NT8daEs7qGKqrK7eJM/Minx/U+iPN4CqtbbrHU11bIZ",
	"W5aMMgPIGOmW4CPVSriKyZNGDbvJeCbUXdeLT7cS9U1/3qEc7o20wOkHJzuyIO5ETvEkv5x4ock5OQXS",
	"muQIC6b4VuqK1JB2LFG0IQ/AdkU8fspaZ8Sd80GFCTmsryEVaxf2/YB32ehTNOROcbMq1WKcuVF2PIIN",
	"MPdKWkDUfV32pmDw3n3xgNoY0JP9rhIHHq96gjNBQkkS3EaKnoKdH2Dj3nNBZ/UTvqojbgUoDT7ydqQE",
	"GH3e4mevVEm94UfEq2xe+pxs2lrgYNiLxaINkgsj6dLuqievnyWdRENE4V22VzDoj5xnes/r3FP2mu3D",
	"y+PiEbHNniCM+qIUXFxc9dxEovLXZLMckGZIbFycnW7SjRncpJk4vhEB+5ZnDK8MvIcJmeKUn/0qCKZb",
	"WPXoD7TNdjFQvlcuWMHe7eA3+2AYEq7wrsguJqjYaLCsTbekaitapet7Yjj9iUdx2T8v22L53uJaP+CB",
	"yQm3wQwIy6VtR4zg/AXG/OtyTXf8R67Lxem3Jnj+Q5q9kRBeHW13LZpQiztFD2Nsyj6FJ/VjrYKJQYxc",
	"LF7+COv4Vg0uIgLSwZnphE8/0sVvEZoHPB3FcpcAHaf8zzJs9YDXtlY9e/S2DTykHvvyK7SWeWVx8eKX",
	"Y6du9uivbh7SLntOu8gtdme8EHUVQmi9EW2WAZvbVw07N9jOi8yWQUhUE7EwmnxsmU8uxfJESX+kAKQL",
	"W/LHELZzselnJMoJpRMAmPwVhouHYDmMeZvtYMTYH0VcvxYpMlYkDZjSKmqhgrfNx7AhEDvjRgAOPWRN",
	"oFwO0vRNJjfm2T4/D1S7MNHcShyv2aJhCADMqmfLpiG7YKTBEiekhopAMlTHf2NvkLlSqHKxI2Ngkzbr",
	"J5fwz2mqF5Bpsz8QsJ39eY+P4xdKeE/p4OL46uzPWMwpEEqrmiIQ5vgS2RA/vQNfY44aX6Tf449MQpXg",
	"A1jpiVua6drkdc6VCF2d/ThVYiu38y5PvKAINXKmCDulbfpOchbYZt3j2CRDbNC2Ycck05jfCeI9UmN/",
	"KCgjx49pAmKUa4WaRu1W4ulXKHvIOQqdMH6DeGXP/0YnTdzABOJoGQ0/SP/+0MSuGuw5+acjLZLOorOR",
	"FilC8FfjJ96qpHtWrDwejrv4wpZsdBwLe+6JTu7Zcon8XaiLV+L0sCflXr8l8JMWbGqtLdTFLUc98f13",
	"nBWPeFiLfpD9NSMHg0PBnKpcUIe9RLphn1MTqdtHJYPfOELIw2tQ5doSLzLt7HUpLViR1oW3NX+TFoaS",
	"6Qzsb/KYTPxcRuo2HDvgxfWvYF+xXFPaldLXh5suO/ruP4B9DUmwIdXRDGpmyVxwGu7CxmXcdTHdls75",
	"xnXSGcqBtJJDhVCaRDld2486FaQkaysX9AmytIeXj5WDg5cjv48XmtsPtv8/AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
