// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/catalog"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// PatchItem provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) PatchItem(ctx context.Context, venueID uuid.UUID, externalID string, patch catalog.MenuItemPatch) (catalog.CategorizedMenuItem, error) {
	ret := _mock.Called(ctx, venueID, externalID, patch)

	if len(ret) == 0 {
		panic("no return value specified for PatchItem")
	}

	var r0 catalog.CategorizedMenuItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, catalog.MenuItemPatch) (catalog.CategorizedMenuItem, error)); ok {
		return returnFunc(ctx, venueID, externalID, patch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, catalog.MenuItemPatch) catalog.CategorizedMenuItem); ok {
		r0 = returnFunc(ctx, venueID, externalID, patch)
	} else {
		r0 = ret.Get(0).(catalog.CategorizedMenuItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, catalog.MenuItemPatch) error); ok {
		r1 = returnFunc(ctx, venueID, externalID, patch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_PatchItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchItem'
type MockMenuRepository_PatchItem_Call struct {
	*mock.Call
}

// PatchItem is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - externalID string
//   - patch catalog.MenuItemPatch
func (_e *MockMenuRepository_Expecter) PatchItem(ctx any, venueID any, externalID any, patch any) *MockMenuRepository_PatchItem_Call {
	return &MockMenuRepository_PatchItem_Call{Call: _e.mock.On("PatchItem", ctx, venueID, externalID, patch)}
}

func (_c *MockMenuRepository_PatchItem_Call) Run(run func(ctx context.Context, venueID uuid.UUID, externalID string, patch catalog.MenuItemPatch)) *MockMenuRepository_PatchItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 catalog.MenuItemPatch
		if args[3] != nil {
			arg3 = args[3].(catalog.MenuItemPatch)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMenuRepository_PatchItem_Call) Return(categorizedMenuItem catalog.CategorizedMenuItem, err error) *MockMenuRepository_PatchItem_Call {
	_c.Call.Return(categorizedMenuItem, err)
	return _c
}

func (_c *MockMenuRepository_PatchItem_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, externalID string, patch catalog.MenuItemPatch) (catalog.CategorizedMenuItem, error)) *MockMenuRepository_PatchItem_Call {
	_c.Call.Return(run)
	return _c
}

// SyncMenu provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) SyncMenu(ctx context.Context, venueID uuid.UUID, snapshot catalog.MenuSnapshot) (catalog.MenuSyncResult, error) {
	ret := _mock.Called(ctx, venueID, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for SyncMenu")
	}

	var r0 catalog.MenuSyncResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, catalog.MenuSnapshot) (catalog.MenuSyncResult, error)); ok {
		return returnFunc(ctx, venueID, snapshot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, catalog.MenuSnapshot) catalog.MenuSyncResult); ok {
		r0 = returnFunc(ctx, venueID, snapshot)
	} else {
		r0 = ret.Get(0).(catalog.MenuSyncResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, catalog.MenuSnapshot) error); ok {
		r1 = returnFunc(ctx, venueID, snapshot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_SyncMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncMenu'
type MockMenuRepository_SyncMenu_Call struct {
	*mock.Call
}

// SyncMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
//   - snapshot catalog.MenuSnapshot
func (_e *MockMenuRepository_Expecter) SyncMenu(ctx any, venueID any, snapshot any) *MockMenuRepository_SyncMenu_Call {
	return &MockMenuRepository_SyncMenu_Call{Call: _e.mock.On("SyncMenu", ctx, venueID, snapshot)}
}

func (_c *MockMenuRepository_SyncMenu_Call) Run(run func(ctx context.Context, venueID uuid.UUID, snapshot catalog.MenuSnapshot)) *MockMenuRepository_SyncMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 catalog.MenuSnapshot
		if args[2] != nil {
			arg2 = args[2].(catalog.MenuSnapshot)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMenuRepository_SyncMenu_Call) Return(menuSyncResult catalog.MenuSyncResult, err error) *MockMenuRepository_SyncMenu_Call {
	_c.Call.Return(menuSyncResult, err)
	return _c
}

func (_c *MockMenuRepository_SyncMenu_Call) RunAndReturn(run func(ctx context.Context, venueID uuid.UUID, snapshot catalog.MenuSnapshot) (catalog.MenuSyncResult, error)) *MockMenuRepository_SyncMenu_Call {
	_c.Call.Return(run)
	return _c
}
