// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/catalog"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVenueRepository creates a new instance of MockVenueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueRepository {
	mock := &MockVenueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVenueRepository is an autogenerated mock type for the VenueRepository type
type MockVenueRepository struct {
	mock.Mock
}

type MockVenueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueRepository) EXPECT() *MockVenueRepository_Expecter {
	return &MockVenueRepository_Expecter{mock: &_m.Mock}
}

// GetVenue provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) GetVenue(ctx context.Context, id uuid.UUID) (catalog.Venue, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVenue")
	}

	var r0 catalog.Venue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (catalog.Venue, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) catalog.Venue); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(catalog.Venue)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_GetVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVenue'
type MockVenueRepository_GetVenue_Call struct {
	*mock.Call
}

// GetVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVenueRepository_Expecter) GetVenue(ctx any, id any) *MockVenueRepository_GetVenue_Call {
	return &MockVenueRepository_GetVenue_Call{Call: _e.mock.On("GetVenue", ctx, id)}
}

func (_c *MockVenueRepository_GetVenue_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVenueRepository_GetVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_GetVenue_Call) Return(venue catalog.Venue, err error) *MockVenueRepository_GetVenue_Call {
	_c.Call.Return(venue, err)
	return _c
}

func (_c *MockVenueRepository_GetVenue_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (catalog.Venue, error)) *MockVenueRepository_GetVenue_Call {
	_c.Call.Return(run)
	return _c
}

// SetShift provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) SetShift(ctx context.Context, id uuid.UUID, open bool) (bool, error) {
	ret := _mock.Called(ctx, id, open)

	if len(ret) == 0 {
		panic("no return value specified for SetShift")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (bool, error)); ok {
		return returnFunc(ctx, id, open)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) bool); ok {
		r0 = returnFunc(ctx, id, open)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, open)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_SetShift_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShift'
type MockVenueRepository_SetShift_Call struct {
	*mock.Call
}

// SetShift is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - open bool
func (_e *MockVenueRepository_Expecter) SetShift(ctx any, id any, open any) *MockVenueRepository_SetShift_Call {
	return &MockVenueRepository_SetShift_Call{Call: _e.mock.On("SetShift", ctx, id, open)}
}

func (_c *MockVenueRepository_SetShift_Call) Run(run func(ctx context.Context, id uuid.UUID, open bool)) *MockVenueRepository_SetShift_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVenueRepository_SetShift_Call) Return(b bool, err error) *MockVenueRepository_SetShift_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockVenueRepository_SetShift_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, open bool) (bool, error)) *MockVenueRepository_SetShift_Call {
	_c.Call.Return(run)
	return _c
}

// VenueByKeyHash provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) VenueByKeyHash(ctx context.Context, hash []byte) (catalog.VenueKey, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for VenueByKeyHash")
	}

	var r0 catalog.VenueKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (catalog.VenueKey, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) catalog.VenueKey); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(catalog.VenueKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_VenueByKeyHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VenueByKeyHash'
type MockVenueRepository_VenueByKeyHash_Call struct {
	*mock.Call
}

// VenueByKeyHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *MockVenueRepository_Expecter) VenueByKeyHash(ctx any, hash any) *MockVenueRepository_VenueByKeyHash_Call {
	return &MockVenueRepository_VenueByKeyHash_Call{Call: _e.mock.On("VenueByKeyHash", ctx, hash)}
}

func (_c *MockVenueRepository_VenueByKeyHash_Call) Run(run func(ctx context.Context, hash []byte)) *MockVenueRepository_VenueByKeyHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_VenueByKeyHash_Call) Return(venueKey catalog.VenueKey, err error) *MockVenueRepository_VenueByKeyHash_Call {
	_c.Call.Return(venueKey, err)
	return _c
}

func (_c *MockVenueRepository_VenueByKeyHash_Call) RunAndReturn(run func(ctx context.Context, hash []byte) (catalog.VenueKey, error)) *MockVenueRepository_VenueByKeyHash_Call {
	_c.Call.Return(run)
	return _c
}
