// Package venueapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package venueapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for KitchenOrderState.
const (
	ACCEPTED KitchenOrderState = "ACCEPTED"
	NEW      KitchenOrderState = "NEW"
	READY    KitchenOrderState = "READY"
	REJECTED KitchenOrderState = "REJECTED"
)

// Valid indicates whether the value is a known member of the KitchenOrderState enum.
func (e KitchenOrderState) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case NEW:
		return true
	case READY:
		return true
	case REJECTED:
		return true
	default:
		return false
	}
}

// AcceptRequest defines model for AcceptRequest.
type AcceptRequest struct {
	// EtaMinutes Если не передано, берётся среднее время готовки заведения.
	EtaMinutes *int `json:"eta_minutes,omitempty"`
}

// Dish defines model for Dish.
type Dish struct {
	IsAvailable bool   `json:"is_available"`
	Name        string `json:"name"`

	// Price Сумма в копейках.
	Price Money  `json:"price"`
	Sku   string `json:"sku"`
	Stock *int   `json:"stock,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
	TraceId *string                 `json:"trace_id,omitempty"`
}

// KitchenOrder defines model for KitchenOrder.
type KitchenOrder struct {
	Comment   *string            `json:"comment,omitempty"`
	DecidedAt *time.Time         `json:"decided_at,omitempty"`
	Items     []KitchenOrderItem `json:"items"`
	Number    string             `json:"number"`

	// OrderId Идентификатор заказа на площадке.
	OrderId    openapi_types.UUID `json:"order_id"`
	ReceivedAt time.Time          `json:"received_at"`

	// State Состояние заказа на кухне: `NEW` — ждёт решения повара, `ACCEPTED` —
	// готовится, `READY` — готов к выдаче, `REJECTED` — отклонён.
	State KitchenOrderState `json:"state"`

	// Total Сумма в копейках.
	Total Money `json:"total"`
}

// KitchenOrderItem defines model for KitchenOrderItem.
type KitchenOrderItem struct {
	Name string `json:"name"`

	// Price Сумма в копейках.
	Price Money  `json:"price"`
	Qty   int    `json:"qty"`
	Sku   string `json:"sku"`
}

// KitchenOrderList defines model for KitchenOrderList.
type KitchenOrderList struct {
	Items []KitchenOrder `json:"items"`
}

// KitchenOrderState Состояние заказа на кухне: `NEW` — ждёт решения повара, `ACCEPTED` —
// готовится, `READY` — готов к выдаче, `REJECTED` — отклонён.
type KitchenOrderState string

// Money Сумма в копейках.
type Money = int64

// RejectRequest defines model for RejectRequest.
type RejectRequest struct {
	Reason string `json:"reason"`
}

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// OrderState defines model for OrderState.
type OrderState = KitchenOrder

// ListKitchenOrdersParams defines parameters for ListKitchenOrders.
type ListKitchenOrdersParams struct {
	// State Фильтр по состоянию заказа на кухне.
	State *[]KitchenOrderState `form:"state,omitempty" json:"state,omitempty"`
}

// AcceptKitchenOrderJSONRequestBody defines body for AcceptKitchenOrder for application/json ContentType.
type AcceptKitchenOrderJSONRequestBody = AcceptRequest

// RejectKitchenOrderJSONRequestBody defines body for RejectKitchenOrder for application/json ContentType.
type RejectKitchenOrderJSONRequestBody = RejectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// StopDish Отправить блюдо в стоп-лист
	// (POST /kitchen/dishes/{sku}/stop)
	StopDish(w http.ResponseWriter, r *http.Request, sku string)
	// ListKitchenOrders Заказы на кухне
	// (GET /kitchen/orders)
	ListKitchenOrders(w http.ResponseWriter, r *http.Request, params ListKitchenOrdersParams)
	// AcceptKitchenOrder Принять заказ
	// (POST /kitchen/orders/{order_id}/accept)
	AcceptKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// MarkKitchenOrderReady Заказ готов
	// (POST /kitchen/orders/{order_id}/ready)
	MarkKitchenOrderReady(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// RejectKitchenOrder Отклонить заказ
	// (POST /kitchen/orders/{order_id}/reject)
	RejectKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// StopDish Отправить блюдо в стоп-лист
// (POST /kitchen/dishes/{sku}/stop)
func (_ Unimplemented) StopDish(w http.ResponseWriter, r *http.Request, sku string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListKitchenOrders Заказы на кухне
// (GET /kitchen/orders)
func (_ Unimplemented) ListKitchenOrders(w http.ResponseWriter, r *http.Request, params ListKitchenOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AcceptKitchenOrder Принять заказ
// (POST /kitchen/orders/{order_id}/accept)
func (_ Unimplemented) AcceptKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// MarkKitchenOrderReady Заказ готов
// (POST /kitchen/orders/{order_id}/ready)
func (_ Unimplemented) MarkKitchenOrderReady(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RejectKitchenOrder Отклонить заказ
// (POST /kitchen/orders/{order_id}/reject)
func (_ Unimplemented) RejectKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// StopDish operation middleware
func (siw *ServerInterfaceWrapper) StopDish(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sku" -------------
	var sku string

	err = runtime.BindStyledParameterWithOptions("simple", "sku", chi.URLParam(r, "sku"), &sku, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sku", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopDish(w, r, sku)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListKitchenOrders operation middleware
func (siw *ServerInterfaceWrapper) ListKitchenOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListKitchenOrdersParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListKitchenOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptKitchenOrder operation middleware
func (siw *ServerInterfaceWrapper) AcceptKitchenOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptKitchenOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkKitchenOrderReady operation middleware
func (siw *ServerInterfaceWrapper) MarkKitchenOrderReady(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkKitchenOrderReady(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectKitchenOrder operation middleware
func (siw *ServerInterfaceWrapper) RejectKitchenOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "order_id" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectKitchenOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/kitchen/orders", wrapper.ListKitchenOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/kitchen/orders/{order_id}/accept", wrapper.AcceptKitchenOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/kitchen/orders/{order_id}/reject", wrapper.RejectKitchenOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/kitchen/orders/{order_id}/ready", wrapper.MarkKitchenOrderReady)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/kitchen/dishes/{sku}/stop", wrapper.StopDish)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type OrderStateJSONResponse KitchenOrder

type StopDishRequestObject struct {
	Sku string `json:"sku"`
}

type StopDishResponseObject interface {
	VisitStopDishResponse(w http.ResponseWriter) error
}

type StopDish200JSONResponse Dish

func (response StopDish200JSONResponse) VisitStopDishResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopDish404JSONResponse struct{ NotFoundJSONResponse }

func (response StopDish404JSONResponse) VisitStopDishResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopDish500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopDish500JSONResponse) VisitStopDishResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListKitchenOrdersRequestObject struct {
	Params ListKitchenOrdersParams
}

type ListKitchenOrdersResponseObject interface {
	VisitListKitchenOrdersResponse(w http.ResponseWriter) error
}

type ListKitchenOrders200JSONResponse KitchenOrderList

func (response ListKitchenOrders200JSONResponse) VisitListKitchenOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListKitchenOrders500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListKitchenOrders500JSONResponse) VisitListKitchenOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptKitchenOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
	Body    *AcceptKitchenOrderJSONRequestBody
}

type AcceptKitchenOrderResponseObject interface {
	VisitAcceptKitchenOrderResponse(w http.ResponseWriter) error
}

type AcceptKitchenOrder200JSONResponse struct{ OrderStateJSONResponse }

func (response AcceptKitchenOrder200JSONResponse) VisitAcceptKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptKitchenOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response AcceptKitchenOrder404JSONResponse) VisitAcceptKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptKitchenOrder409JSONResponse struct{ ConflictJSONResponse }

func (response AcceptKitchenOrder409JSONResponse) VisitAcceptKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptKitchenOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response AcceptKitchenOrder500JSONResponse) VisitAcceptKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type MarkKitchenOrderReadyRequestObject struct {
	OrderId OrderId `json:"order_id"`
}

type MarkKitchenOrderReadyResponseObject interface {
	VisitMarkKitchenOrderReadyResponse(w http.ResponseWriter) error
}

type MarkKitchenOrderReady200JSONResponse struct{ OrderStateJSONResponse }

func (response MarkKitchenOrderReady200JSONResponse) VisitMarkKitchenOrderReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type MarkKitchenOrderReady404JSONResponse struct{ NotFoundJSONResponse }

func (response MarkKitchenOrderReady404JSONResponse) VisitMarkKitchenOrderReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type MarkKitchenOrderReady409JSONResponse struct{ ConflictJSONResponse }

func (response MarkKitchenOrderReady409JSONResponse) VisitMarkKitchenOrderReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type MarkKitchenOrderReady500JSONResponse struct{ InternalErrorJSONResponse }

func (response MarkKitchenOrderReady500JSONResponse) VisitMarkKitchenOrderReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RejectKitchenOrderRequestObject struct {
	OrderId OrderId `json:"order_id"`
	Body    *RejectKitchenOrderJSONRequestBody
}

type RejectKitchenOrderResponseObject interface {
	VisitRejectKitchenOrderResponse(w http.ResponseWriter) error
}

type RejectKitchenOrder200JSONResponse struct{ OrderStateJSONResponse }

func (response RejectKitchenOrder200JSONResponse) VisitRejectKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RejectKitchenOrder400JSONResponse struct{ BadRequestJSONResponse }

func (response RejectKitchenOrder400JSONResponse) VisitRejectKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RejectKitchenOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response RejectKitchenOrder404JSONResponse) VisitRejectKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RejectKitchenOrder409JSONResponse struct{ ConflictJSONResponse }

func (response RejectKitchenOrder409JSONResponse) VisitRejectKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RejectKitchenOrder500JSONResponse struct{ InternalErrorJSONResponse }

func (response RejectKitchenOrder500JSONResponse) VisitRejectKitchenOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// StopDish Отправить блюдо в стоп-лист
	// (POST /kitchen/dishes/{sku}/stop)
	StopDish(ctx context.Context, request StopDishRequestObject) (StopDishResponseObject, error)
	// ListKitchenOrders Заказы на кухне
	// (GET /kitchen/orders)
	ListKitchenOrders(ctx context.Context, request ListKitchenOrdersRequestObject) (ListKitchenOrdersResponseObject, error)
	// AcceptKitchenOrder Принять заказ
	// (POST /kitchen/orders/{order_id}/accept)
	AcceptKitchenOrder(ctx context.Context, request AcceptKitchenOrderRequestObject) (AcceptKitchenOrderResponseObject, error)
	// MarkKitchenOrderReady Заказ готов
	// (POST /kitchen/orders/{order_id}/ready)
	MarkKitchenOrderReady(ctx context.Context, request MarkKitchenOrderReadyRequestObject) (MarkKitchenOrderReadyResponseObject, error)
	// RejectKitchenOrder Отклонить заказ
	// (POST /kitchen/orders/{order_id}/reject)
	RejectKitchenOrder(ctx context.Context, request RejectKitchenOrderRequestObject) (RejectKitchenOrderResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// StopDish operation middleware
func (sh *strictHandler) StopDish(w http.ResponseWriter, r *http.Request, sku string) {
	var request StopDishRequestObject

	request.Sku = sku

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopDish(ctx, request.(StopDishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopDish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopDishResponseObject); ok {
		if err := validResponse.VisitStopDishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListKitchenOrders operation middleware
func (sh *strictHandler) ListKitchenOrders(w http.ResponseWriter, r *http.Request, params ListKitchenOrdersParams) {
	var request ListKitchenOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListKitchenOrders(ctx, request.(ListKitchenOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListKitchenOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListKitchenOrdersResponseObject); ok {
		if err := validResponse.VisitListKitchenOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptKitchenOrder operation middleware
func (sh *strictHandler) AcceptKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request AcceptKitchenOrderRequestObject

	request.OrderId = orderId

	var body AcceptKitchenOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptKitchenOrder(ctx, request.(AcceptKitchenOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptKitchenOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptKitchenOrderResponseObject); ok {
		if err := validResponse.VisitAcceptKitchenOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkKitchenOrderReady operation middleware
func (sh *strictHandler) MarkKitchenOrderReady(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request MarkKitchenOrderReadyRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkKitchenOrderReady(ctx, request.(MarkKitchenOrderReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkKitchenOrderReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkKitchenOrderReadyResponseObject); ok {
		if err := validResponse.VisitMarkKitchenOrderReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RejectKitchenOrder operation middleware
func (sh *strictHandler) RejectKitchenOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request RejectKitchenOrderRequestObject

	request.OrderId = orderId

	var body RejectKitchenOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RejectKitchenOrder(ctx, request.(RejectKitchenOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RejectKitchenOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RejectKitchenOrderResponseObject); ok {
		if err := validResponse.VisitRejectKitchenOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FltbxvHEf4rh20/nknacYqW/aTIKqomcQ3ZQFBYhrQmV9JFvDv6bmlYEAjwpX4JpFh1kKL90rgB+gMo",
	"lSedJJL6C7N/ob+kmNk73gtPopwqQdsvEo+3Ozsvz8w8s9xlNdduuo5wpM+qu6zJPW4LKTx6+r1XF95y",
	"HT/WhV/zrKa0XIdVGfwVhhDAWPUgVH+EEM5goHowUR0DTmCAj/jfgDH+uYBzmKivYABDOIOgxExmoZQm",
	"l1vMZA63BasyFw9bs+rMZJ541rI8UWdV6bWEyfzalrA5qrHhejaXrMpaLVopd5q415ee5WyydruNm/2m",
	"6/iCLPiE11fEs5bwJT7VXEcKhz7yZrNh1TjaU/7SR6N2U8f83BMbrMp+Vk68U9Zv/fKS57mePirnlL/A",
	"AC5UByaqi5YHRvT0Rr2DcwOOYADnEMIQBuoVhOota5ts0XU2Glbtp1DvWwjgVHVVD44gTLTrQQhHGDoI",
	"1GsIVc9QPQjgTPXVVxDASPUN1UWbKMAHMEbVM2FGO5YdKTyHN/TxP74x38BY9VUPtYYxjNWBOjDQ1RDC",
	"IeqFOt135W/cllP/iUJP3jAgxCAbcAjn6i0MYRJBYQwDOI2yZg+1o+R6KLkUN6bfp5asbQmHJM9T8wJD",
	"Cueo2jANDPTjBUwQraqDfmzH+UcJtVCriaZM5VTTc5vCk5bONyH5mm05Lakfc8f/mU4M4+SAgMI3hAGM",
	"YWKizwLVUe9UT3XVgaG60esxBLj+iB5HqOA/Cbeo5BmKQywe0dKA4HmAJcbmLyy7ZbPqnbsVk9mWo59u",
	"T4uG5UixSY6afuU+/VLUJEbnnuVvzZpn+Wv8Obca/GmDohZte+q6DcEd3KeL2W6+MJms6Vk1MS+An7uO",
	"2MHV/narUIov3do2vnFajUgLXSILbEqq6GOSFykXq2JmrXlS4IRpMme9UHPrxTbWheRWg9bwet3CsPPG",
	"g9TejK7JObbwfb5ZLFN6vCawLcy+zNlIaiXCigzKJEiBXbYd5WCBaTWrLuprXGbaUJ1LcUta5NZLQpLI",
	"sKSwNYziD9dN5mUpbJbAlHseJ5g4LfuptmTmsGk7vfnmPacJY1Rqwnp+tbcKoB2Vwus6RddO9IoreeOa",
	"qZXDTIp0RL6MFYnDFYvPWjUPXBSwGYDdUHF4JndSUqYpf1nVuE4pQJHzbPrMKqr4PxzUs4DOaaolzlNr",
	"2kJzKP8+y1mwg8yiG1nOS2wwVWP9/tIX68a/Ot8acAxD7EIGcaI3cVPJ9EXTWF9YXFx68GjpHm1adVJN",
	"KdQdzDTWV5YW7v0hkjp9b8AZdrM9YoKvIaB1v1tajGUZtPAMEw/G6h2MS6sOM5lwsH89ZveXvmAmi09n",
	"JqND6L8WknJZAjGNngI3qT6MYITOQMVggn0ZTqkovMxku+XIX9xlqVZaMQswuCIwSJcSBE/wiNLY/MVn",
	"wtmUW6z6cUV36Pj5tjkHw5GUWWjgQsvZcAsMzTFGCOHUWHiwrOnPCCa3VJcICYavi+6YZRUGvM9Uw4EB",
	"AYY1IjQY0hO1R0Q/UL2qob7GgBvqazhDzMB41UljyNBUKEQMaDGHMIFztY+YKxkJW1N7Rlo5DcRz1Vev",
	"9UlIOk+MT/nGNjcNGBiE+4Hqqb7q4t43cE54hiNSIGWC6qOwgeqoHkJNdVQXKRWMjJWlh48iMMIhpQrR",
	"NBxhBvjdGA9F5V9BCKHqqD5pgq6DUWnVWXXgT+jvmU5D68lj5KKMXcc4i0SqajCOyYpOnL3ZeNApf4cA",
	"tVL7SKzhNGcPjl0TpLmoMEUphBEerfZxzhnQIeh7ggKuPUKVtOUneJbqqv3IYHR7FJA4yPhmiJ5Az1KQ",
	"j5D009IhuU5rpboR457AIdWVaBg8mXokguahxkcEUKwUebvfaru/IT2jbwM4poMQhRCgZJzl8CuyRL2i",
	"LycQGDTjIQ2fJNkewJkuMdKSyF/0rIg5kT888kyC6OywYLLnwvN1wt0uVUoVYiJN4fCmxarso1Kl9BF2",
	"HS63qBqUt3UhL9ctf0v45V1/u9Uu+9JtUuVwdQXJJfK7ZLLSCHlNMxdW+/2SAd+nAKW6pPQojpVOM8og",
	"nH1p9DhG39OMG8AhVvkwM5roRkCJnE8e7U298sRYf7DwaPG3RrnJPekIr2wLp1WmFlbeFS/0dLxm1dvr",
	"2tVYFGnGW66zKnso3SaNHGbmCubxh3C3eOLUlXwMEwQ6jKmRDK5Ko+L7GM0TLr+KSdXv23d+Oa9+P8ld",
	"zNypVG5s7CXHFY27CVIQCOpAV+N89BGjdyt3LztlqnZ5ep/QNtnHWv+rN2QvRWiSbtk293ZQue9Ub1ox",
	"QqpH6TuDI13EJ3Bxi7K5q3qYn3wTUcF0urAnKHKaQ8RlybmbgjyahRjStzRv8udi7R+YV2ofCxOl+bx7",
	"oDynQmCJF80GjYsaPoSzZy3h7aSAFvHtJNgfTCWTUSDLJ39M1M1Q4ysvXNSeGbflDtVp1cUsVB31UvVv",
	"BlBpupCLRAo6EUqKoFPejcehdpnTPc8VVfh9XPZ1BxjS7RHWwmPKKyq3U2z8Oj9HDgzVhxPUUnd76opU",
	"ZGF0FSMpzVROfSGVmStmcF3k1GRJOb7m1nAh4vqJW9+5MaRk78zas7fUd64T+yzQP7hg3a38av6G6W30",
	"jQDyveoQBznQ1W2Khg9Hoye4jkcMxiwGPufedhoBK7T8P4PB/394UpfB09H0h4SGJq9LY6Pnwf/q/MyO",
	"rO3ssIl960by9RpbUr9W/Y9g6LvkoiImMVenOW4X3vM48i2vwaqsTKGNFu9e0UN1X0umD/0zQnr+SP+Y",
	"6LO2OSPtb4W8uGjcT6RFdKv9pP3vAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
