// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeliveries creates a new instance of MockDeliveries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveries {
	mock := &MockDeliveries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveries is an autogenerated mock type for the Deliveries type
type MockDeliveries struct {
	mock.Mock
}

type MockDeliveries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveries) EXPECT() *MockDeliveries_Expecter {
	return &MockDeliveries_Expecter{mock: &_m.Mock}
}

// Deliver provides a mock function for the type MockDeliveries
func (_mock *MockDeliveries) Deliver(ctx context.Context, before time.Time, limit int) (int, error) {
	ret := _mock.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for Deliver")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int, error)); ok {
		return returnFunc(ctx, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int); ok {
		r0 = returnFunc(ctx, before, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveries_Deliver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deliver'
type MockDeliveries_Deliver_Call struct {
	*mock.Call
}

// Deliver is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - limit int
func (_e *MockDeliveries_Expecter) Deliver(ctx any, before any, limit any) *MockDeliveries_Deliver_Call {
	return &MockDeliveries_Deliver_Call{Call: _e.mock.On("Deliver", ctx, before, limit)}
}

func (_c *MockDeliveries_Deliver_Call) Run(run func(ctx context.Context, before time.Time, limit int)) *MockDeliveries_Deliver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeliveries_Deliver_Call) Return(n int, err error) *MockDeliveries_Deliver_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDeliveries_Deliver_Call) RunAndReturn(run func(ctx context.Context, before time.Time, limit int) (int, error)) *MockDeliveries_Deliver_Call {
	_c.Call.Return(run)
	return _c
}
