// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeys creates a new instance of MockKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeys {
	mock := &MockKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeys is an autogenerated mock type for the Keys type
type MockKeys struct {
	mock.Mock
}

type MockKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeys) EXPECT() *MockKeys_Expecter {
	return &MockKeys_Expecter{mock: &_m.Mock}
}

// DeleteExpired provides a mock function for the type MockKeys
func (_mock *MockKeys) DeleteExpired(ctx context.Context, limit int) (int64, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockKeys_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockKeys_Expecter) DeleteExpired(ctx any, limit any) *MockKeys_DeleteExpired_Call {
	return &MockKeys_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx, limit)}
}

func (_c *MockKeys_DeleteExpired_Call) Run(run func(ctx context.Context, limit int)) *MockKeys_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeys_DeleteExpired_Call) Return(n int64, err error) *MockKeys_DeleteExpired_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKeys_DeleteExpired_Call) RunAndReturn(run func(ctx context.Context, limit int) (int64, error)) *MockKeys_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}
