// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"avito-kitchen/internal/domain/outbox"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessages creates a new instance of MockMessages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessages(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessages {
	mock := &MockMessages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessages is an autogenerated mock type for the Messages type
type MockMessages struct {
	mock.Mock
}

type MockMessages_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessages) EXPECT() *MockMessages_Expecter {
	return &MockMessages_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockMessages
func (_mock *MockMessages) Fetch(ctx context.Context, limit int) ([]outbox.Pending, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []outbox.Pending
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]outbox.Pending, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []outbox.Pending); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Pending)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessages_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockMessages_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockMessages_Expecter) Fetch(ctx any, limit any) *MockMessages_Fetch_Call {
	return &MockMessages_Fetch_Call{Call: _e.mock.On("Fetch", ctx, limit)}
}

func (_c *MockMessages_Fetch_Call) Run(run func(ctx context.Context, limit int)) *MockMessages_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessages_Fetch_Call) Return(pendings []outbox.Pending, err error) *MockMessages_Fetch_Call {
	_c.Call.Return(pendings, err)
	return _c
}

func (_c *MockMessages_Fetch_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]outbox.Pending, error)) *MockMessages_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockMessages
func (_mock *MockMessages) MarkFailed(ctx context.Context, id int64, cause error) error {
	ret := _mock.Called(ctx, id, cause)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error) error); ok {
		r0 = returnFunc(ctx, id, cause)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessages_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockMessages_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - cause error
func (_e *MockMessages_Expecter) MarkFailed(ctx any, id any, cause any) *MockMessages_MarkFailed_Call {
	return &MockMessages_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, cause)}
}

func (_c *MockMessages_MarkFailed_Call) Run(run func(ctx context.Context, id int64, cause error)) *MockMessages_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessages_MarkFailed_Call) Return(err error) *MockMessages_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessages_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, id int64, cause error) error) *MockMessages_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function for the type MockMessages
func (_mock *MockMessages) MarkPublished(ctx context.Context, ids []int64) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessages_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockMessages_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockMessages_Expecter) MarkPublished(ctx any, ids any) *MockMessages_MarkPublished_Call {
	return &MockMessages_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, ids)}
}

func (_c *MockMessages_MarkPublished_Call) Run(run func(ctx context.Context, ids []int64)) *MockMessages_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessages_MarkPublished_Call) Return(err error) *MockMessages_MarkPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessages_MarkPublished_Call) RunAndReturn(run func(ctx context.Context, ids []int64) error) *MockMessages_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}
