// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrders creates a new instance of MockOrders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrders {
	mock := &MockOrders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrders is an autogenerated mock type for the Orders type
type MockOrders struct {
	mock.Mock
}

type MockOrders_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrders) EXPECT() *MockOrders_Expecter {
	return &MockOrders_Expecter{mock: &_m.Mock}
}

// Reap provides a mock function for the type MockOrders
func (_mock *MockOrders) Reap(ctx context.Context, before time.Time, limit int) (int, error) {
	ret := _mock.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for Reap")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int, error)); ok {
		return returnFunc(ctx, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int); ok {
		r0 = returnFunc(ctx, before, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Reap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reap'
type MockOrders_Reap_Call struct {
	*mock.Call
}

// Reap is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - limit int
func (_e *MockOrders_Expecter) Reap(ctx any, before any, limit any) *MockOrders_Reap_Call {
	return &MockOrders_Reap_Call{Call: _e.mock.On("Reap", ctx, before, limit)}
}

func (_c *MockOrders_Reap_Call) Run(run func(ctx context.Context, before time.Time, limit int)) *MockOrders_Reap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrders_Reap_Call) Return(n int, err error) *MockOrders_Reap_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOrders_Reap_Call) RunAndReturn(run func(ctx context.Context, before time.Time, limit int) (int, error)) *MockOrders_Reap_Call {
	_c.Call.Return(run)
	return _c
}
